build.sbt, docs/developer_guide.md, project/Versions.scala
@LinuxUser404 
Usage:
```
$ sbt -Dhive.jdbc.version=1.2.1.spark2 dependencyList | grep hive-jdbc
[info] org.spark-project.hive:hive-jdbc:1.2.1.spark2
$ sbt -Dhive.jdbc.version=upstream dependencyList | grep hive-jdbc
[info] org.spark-project.hive:hive-jdbc:1.2.1.spark2
$ sbt dependencyList | grep hive-jdbc
[info] org.spark-project.hive:hive-jdbc:1.2.1.spark2.kamu.1
```
So in travis build we can set `-Dhive.jdbc.version=upstream`.
=> Allow dynamically override hive dependency version

CHANGELOG.md, kamu-cli/src/cli_commands.rs, kamu-cli/src/cli_parser.rs, kamu-cli/src/commands/log_command.rs
This PR adds two workarounds for poor pagination performance on datasets with high block counts.
1) Individual writes into `minus::Pager` seem to have high overhead, so we format the entire block using a temporary buffer and only write to `Pager` once per block.
This already improves performance significanlty (e.g. `kamu log` on a 1000-block dataset takes about 3 seconds to render).
2) On top of that to limit performance degradation we introduce `--limit` parameter to the `log` command that defaults to 500 blocks.
Note:
* `kamu log x > file` is blazing fast even with 1K blocks, so its all overhead is in the `minus` pager library
* `minus` library has support for "dynamic paging" where a separate thread can push more data progressively but it doesn't work as I expected - it doesn't …
=> Improve paginator performance on large block counts

CHANGELOG.md, kamu-core/src/infra/pull_service_impl.rs, kamu-core/tests/tests/test_pull_service_impl.rs
```bash
$ kamu list
┌─────────────────────────────────┬──────┬────────┬─────────┬──────┐
│              Name               │ Kind │ Pulled │ Records │ Size │
├─────────────────────────────────┼──────┼────────┼─────────┼──────┤
│ com.cryptocompare.ohlcv.eth-usd │ Root │   -    │       - │    - │
└─────────────────────────────────┴──────┴────────┴─────────┴──────┘
$ kamu pull zzz
thread 'main' panicked at 'called `Option::unwrap()` on a `None` value', kamu-core/src/infra/pull_service_impl.rs:165:45
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```
=> Fix panic on pulling non-existing dataset

CHANGELOG.md, README.md, utils/installer/Makefile, utils/installer/kamu-install.sh
Adding an installer script that can be used via `curl -s "https://get.kamu.dev" | sh`
By default it will install to `~/.local/bin/kamu`
For development it's great to have your dev build of kamu as a symbolic link:
```sh
~/.local/bin/kamu -> /<wherever>/kamu-cli/target/debug/kamu-cli
```
and have the release version installed for testing under the `kamu-release` name - this can be done via:
```sh
curl -s "https://get.kamu.dev" | KAMU_ALIAS=kamu-release sh
```
=> Add installer script

CHANGELOG.md, Cargo.lock, LICENSE.txt, images/Makefile, images/demo/Makefile, kamu-adapter-graphql/Cargo.toml, kamu-cli/Cargo.toml, kamu-cli/src/commands/list_command.rs, kamu-cli/src/commands/sql_shell_command.rs, kamu-cli/src/commands/tail_command.rs, kamu-cli/src/output/output_config.rs, kamu-cli/src/output/records_writers.rs, kamu-core/Cargo.toml, opendatafabric/Cargo.toml, utils/container-runtime/Cargo.toml
Previously `kamu list` was using a completely custom output than the rest of the tabular output commands (e.g. `kamu tail`, `kamu sql -c`) because it needed some custom formatting that was not available for `RecordsBatch`es.
This PR unifies tabular output allowing you to specify custom formatting rules per column. This allows `kamu list --output-fromat <json/json-ld/...>` to work, which is very useful for scripting and automation.
=> Unified table output

CHANGELOG.md, Cargo.lock, LICENSE.txt, examples/reth-vs-snp500/analysis.ipynb, images/Makefile, images/demo/Makefile, kamu-adapter-graphql/Cargo.toml, kamu-cli/Cargo.toml, kamu-core/Cargo.toml, kamu-core/src/infra/utils/docker_images.rs, opendatafabric/Cargo.toml, utils/container-runtime/Cargo.toml
flink engine 0.15.1 fixes the crash on checkpoints over 5MiB large
=> Upgrade flink engine

CHANGELOG.md, kamu-adapter-graphql/src/queries/data.rs, kamu-adapter-graphql/src/queries/dataset_data.rs, kamu-adapter-graphql/src/queries/dataset_metadata.rs, kamu-adapter-graphql/src/scalars/dataset.rs, kamu-cli/src/commands/inspect_schema_command.rs, kamu-core/src/domain/query_service.rs, kamu-core/src/infra/query_service_impl.rs, resources/schema.gql
CLI:
- kamu inspect schema prints a warning
- kamu tail prints an error
GraphQL adapter:
- optional schema access taken into account
- empty tail when there is no schema
=> Handling situations when dataset schema is not yet defined

Cargo.lock, LICENSE.txt, images/Makefile, images/demo/Makefile, kamu-adapter-graphql/Cargo.toml, kamu-adapter-graphql/src/queries/datasets.rs, kamu-adapter-graphql/src/queries/metadata_chain.rs, kamu-adapter-graphql/src/scalars/dataset.rs, kamu-adapter-graphql/src/scalars/metadata.rs, kamu-adapter-graphql/src/scalars/odf_generated.rs, kamu-adapter-graphql/tests/tests/mod.rs, kamu-adapter-graphql/tests/tests/test_api_server_command.rs, kamu-adapter-graphql/tests/tests/test_gql_datasets.rs, kamu-adapter-graphql/tests/tests/test_gql_metadata_chain.rs, kamu-cli/Cargo.toml, kamu-cli/tests/tests/mod.rs, kamu-core/Cargo.toml, opendatafabric/Cargo.toml, opendatafabric/src/serde/serdes.rs, opendatafabric/src/serde/yaml/serdes.rs, resources/schema.gql, utils/container-runtime/Cargo.toml
Adds dataset creation APIs:
```gql
"""
Creates a new empty dataset
"""
createEmpty(accountId: AccountID!, datasetKind: DatasetKind!, datasetName: DatasetName!): CreateDatasetResult!
"""
Creates a new dataset from provided DatasetSnapshot manifest
"""
createFromSnapshot(accountId: AccountID!, datasetSnapshot: String!, datasetSnapshotFormat: MetadataManifestFormat!): CreateDatasetFromSnapshotResult!
```
Also adds a convenience method to get raw metadata block (e.g. in YAML format):
```gql
"""
Returns a metadata block corresponding to the specified hash and encoded in desired format
"""
blockByHashRaw(hash: Multihash!, blockFormat: MetadataManifestFormat!): String
```
And looking ahead - a new method for appending metadata events to a chain:
```gql
"""
Commits new event to the metadata chain …
```
=> GQL dataset creation and append APIs

CHANGELOG.md, Cargo.lock, LICENSE.txt, images/Makefile, images/demo/Makefile, kamu-adapter-graphql/Cargo.toml, kamu-cli/Cargo.toml, kamu-cli/src/app.rs, kamu-cli/src/cli_commands.rs, kamu-cli/src/cli_parser.rs, kamu-cli/src/commands/add_command.rs, kamu-cli/tests/tests/mod.rs, kamu-cli/tests/tests/test_add_command.rs, kamu-cli/tests/utils/kamu.rs, kamu-core/Cargo.toml, opendatafabric/Cargo.toml, opendatafabric/src/serde/yaml/serdes.rs, utils/container-runtime/Cargo.toml
- Adds `--stdin` flag to `kamu add` command
- Improved heuristics that detects if YAML file is a `DatasetSnapshot` during `kamu add --recursive <dir>` to ignore comments
=> Support kamu add from STDIN

.github/workflows/build.yaml, .github/workflows/release.yaml, CHANGELOG.md, Cargo.toml, DEVELOPER.md, kamu-cli/src/cli_commands.rs, kamu-cli/src/cli_parser.rs, kamu-cli/src/commands/pull_images_command.rs, kamu-core/src/testing/minio_server.rs, kamu-core/tests/tests/mod.rs, kamu-core/tests/tests/test_setup.rs, kamu-core/tests/utils/ftp_server.rs, kamu-core/tests/utils/http_server.rs, utils/container-runtime/src/container_runtime.rs, utils/installer/kamu-install.sh
In this PR:
- Avoiding multiple recompilations in Linux CI build job by avoiding calls to `cargo run --bin kamu-cli`
- Avoiding workspace feature unification in CI release job by compiling a specific crate
- Using `debug=1` on our crates in release build to have line information in backtraces
=> Build improvements

.github/workflows/build.yaml, .github/workflows/release.yaml, Cargo.toml, kamu-cli/src/app.rs
I previously tried caching unsuccessfully, and this guide provides some info on why caching `./target` dir doesn't work well. This PR uses a rust-specific cache action that is relied upon by >1K projects.
Upon successful hit, caching reduces CI build time by ~8 minutes.
Additionally I'm following [this guide](https://matklad.github.io/2021/09/04/fast-rust-builds.html#CI-Workflow) to create a custom `ci` profile in cargo that should speed up build further (see `Cargo.toml` changes).
=> Use rust-cache action

.config/nextest.toml, .github/workflows/build.yaml, Cargo.lock, DEVELOPER.md, Makefile, src/adapter/graphql/Cargo.toml, src/adapter/http/Cargo.toml, src/adapter/http/tests/tests/tests_pull/test_smart_pull_s3.rs, src/adapter/http/tests/tests/tests_push/test_smart_push_s3.rs, src/app/cli/Cargo.toml, src/app/cli/tests/tests/test_pull_command.rs, src/infra/core/Cargo.toml, src/infra/core/tests/tests/engine/test_ingest_engine.rs, src/infra/core/tests/tests/engine/test_transform_engine.rs, src/infra/core/tests/tests/ingest/test_fetch.rs, src/infra/core/tests/tests/repos/test_dataset_repository_local_fs.rs, src/infra/core/tests/tests/repos/test_dataset_repository_s3.rs, src/infra/core/tests/tests/repos/test_named_object_repository.rs, src/infra/core/tests/tests/repos/test_object_repository_s3.rs, src/infra/core/tests/tests/test_query_service_impl.rs, src/infra/core/tests/tests/test_search_service_impl.rs, src/infra/core/tests/tests/test_setup.rs, src/infra/core/tests/tests/test_sync_service_impl.rs, src/utils/container-runtime/Cargo.toml, src/utils/container-runtime/tests/tests/test_container.rs, src/utils/container-runtime/tests/tests/test_network.rs, src/utils/container-runtime/tests/tests/test_setup.rs
Using `nextest` to control concurrency of tests (esp. those that start engines) and add retries to our "flaky" container tests.
To group tests without changing our module structure or hard-coding tests names I created a tiny [test-group](https://crates.io/crates/test-group) crate.
=> Use nextest runner

CHANGELOG.md, Cargo.lock, Cargo.toml, src/app/cli/Cargo.toml, src/app/cli/src/app.rs, src/infra/core/src/repos/dataset_impl.rs, src/infra/core/src/transform_service_impl.rs, src/infra/core/src/utils/cached_object.rs, src/infra/core/src/verification_service_impl.rs, src/utils/tracing-perfetto/Cargo.toml, src/utils/tracing-perfetto/examples/example.rs, src/utils/tracing-perfetto/src/json_writer.rs, src/utils/tracing-perfetto/src/layer.rs, src/utils/tracing-perfetto/src/lib.rs, src/utils/tracing-perfetto/src/perfetto_types.rs
After some discussion with the author of `tracing-chrome` crate, and asking around in Perfetto dev Discord I decided to prototype my own tracer.
It works as follows:
* every time span is entered / exited it writes **synchronous** begin/end timelines - thus giving us a nice stacked per-thread flame graph for each time a coroutine was actively running on a CPU
* when span is created / closed it writes **async** begin/end timelines under unique timeline IDs - this gives us independent async timeline per every span in the program (similarly to how Jaeger displays spans)
It's not perfect but much better than what we had before.
Here's an example of pulling two datasets concurrently using old tracer:
and here is the new one:
=> Custom perfetto layer

.github/workflows/build.yaml, CHANGELOG.md, Cargo.lock, Cross.toml, installer/kamu-install.sh, src/app/cli/Cargo.toml, src/app/cli/build.rs, src/app/cli/src/cli_commands.rs, src/app/cli/src/cli_parser.rs, src/app/cli/src/commands/mod.rs, src/app/cli/src/commands/system_info_command.rs, src/app/cli/tests/tests/test_system_info_command.rs
Something I wanted to add for a long time.
Example output:
After this is in place we can add a github issue template to this repo asking people to always submit this info when reporting problems.
I'm planning to add a similar (admin-only) endpoint to the `api-server` as well.
=> System info command

CHANGELOG.md, Cargo.lock, Cargo.toml, LICENSE.txt, deny.toml, examples/README.md, examples/flight-sql/README.md, examples/flight-sql/python/client_flightsql_dbapi2.py, examples/flight-sql/python/client_flightsql_sqlalchemy.py, examples/flight-sql/python/client_jdbc.py, examples/flight-sql/python/requirements.txt, src/adapter/flight-sql/Cargo.toml, src/adapter/flight-sql/src/lib.rs, src/adapter/flight-sql/src/service.rs, src/adapter/flight-sql/src/service_builder.rs, src/adapter/flight-sql/src/session_factory.rs, src/adapter/flight-sql/tests/tests/test_service.rs, src/app/cli/Cargo.toml, src/app/cli/src/commands/sql_server_flightsql_command.rs
Rustc was choking when my async callback for creating DataFusion sessions per user got a bit complex, so the main change here was to replace a functor with a `SessionFactory` async trait interface.
I also used this opportunity to include python FlightSQL client code into examples.
=> FlightSQL tweaks

src/adapter/http/src/api_error.rs, src/adapter/http/src/data/ingest_handler.rs, src/adapter/http/src/lib.rs, src/adapter/http/src/middleware/authentication_layer.rs, src/adapter/http/src/simple_protocol/handlers.rs
An attempt to add a generic error handling mechanism to REST API, similar to how I did with GQL.
Main goal is to enable uniform logging in a single place rather than relying on every handler not forgetting to log the error. I ran into this when implementing push endpoint where many errors were just swallowed giving me no visibility even under debug logging.
=> Improve HTTP API error handling

DEVELOPER.md
To speed up the installation a bit, we add confirmation (`-y`) for the `cargo binstall *` commands
=> Developer Guide: add -y for cargo binstall commands

CHANGELOG.md, src/app/cli/src/services/workspace/workspace_service.rs
Useful for test and debug activities -- to be able to run a debugger with the custom workspace path (e.g. from an IDE)
=> Use KAMU_WORKSPACE envvar to find a workspace

src/app/cli/src/services/workspace/workspace_layout.rs, src/domain/core/src/services/ingest/polling_ingest_service.rs, src/infra/core/src/ingest/fetch_service.rs, src/infra/core/src/utils/docker_images.rs, src/infra/core/tests/tests/ingest/test_fetch.rs, src/utils/repo-tools/src/release.rs
Related issue: https://github.com/kamu-data/kamu-cli/issues/302
=> Support input limits and `has_more` loop in containerized ingest

CHANGELOG.md, Cargo.lock, src/infra/core/Cargo.toml, src/infra/core/tests/tests/ingest/test_fetch.rs
- Context: OperationID is used for container name generation. For parallel test running, we had several failed attempts to create a container with the same name.
=> tests::ingest::test_fetch::*: fix race condition during parallel execution

Cargo.toml, src/adapter/graphql/src/queries/datasets/dataset_data.rs, src/domain/core/src/entities/metadata_stream.rs, src/infra/flow-system-inmem/src/services/flow_configuration/flow_configuration_service_inmem.rs, src/infra/task-system-inmem/src/task_scheduler_inmem.rs, src/utils/container-runtime/src/runtime.rs
Fixed clippy warnings
- `pedantic::redundant_else`
Disabled rules
- `pedantic::single_match_else`
- `pedantic::default_trait_access`
Related issue: https://github.com/kamu-data/kamu-cli/issues/332
=> clippy: fix pedantic warnings (redundant_else) and disable rules (single_match_else, default_trait_access)

CHANGELOG.md, resources/schema.gql, src/adapter/graphql/src/mutations/flows_mut/dataset_flow_configs_mut.rs, src/adapter/graphql/src/scalars/flow_configuration.rs, src/adapter/graphql/tests/tests/test_gql_dataset_flow_configs.rs, src/domain/flow-system/src/entities/shared/schedule.rs, src/domain/flow-system/src/lib.rs
Closes: #459
CRON expressions API should accept only classic 5-component syntax (min hour dayOfMonth month dayOfWeek). Years and seconds are forbidden.
=> CRON expressions should allow only classic 5-component syntax

CHANGELOG.md, Cargo.lock, Cargo.toml, deny.toml, src/app/cli/Cargo.toml, src/app/cli/src/commands/sql_shell_command.rs, src/utils/datafusion-cli/Cargo.toml, src/utils/datafusion-cli/LICENSE.txt, src/utils/datafusion-cli/README.md, src/utils/datafusion-cli/src/catalog.rs, src/utils/datafusion-cli/src/command.rs, src/utils/datafusion-cli/src/exec.rs, src/utils/datafusion-cli/src/functions.rs, src/utils/datafusion-cli/src/helper.rs, src/utils/datafusion-cli/src/lib.rs, src/utils/datafusion-cli/src/object_storage.rs, src/utils/datafusion-cli/src/print_format.rs, src/utils/datafusion-cli/src/print_options.rs, src/utils/repo-tools/tests/lints/license_header.rs
Closes: [<#issue>](https://github.com/kamu-data/kamu-cli/issues/228) DataFusion-based SQL console #228
Job done:
1. Linked datafusion-cli as a dependency of kamu-cli.
2. Allowed launching datafusion-cli via kamu sql, made datafusion the default engine for kamu sql command.
3. added BSL-1.0 to licenses after running cargo deny check.
1. kamu sql => datafusion-cli:
2. kamu --sql --command "select 1": datafusion engine:
**NB! Testing will be added in next PR.**
=> DataFusion-based SQL console #228:

src/app/cli/src/cli_parser.rs
Fixes a regression introduced in cf1682aecf96af9ec0913b170401dbbd4828712e
```
$ kamu tail gps
thread 'main' panicked at src/app/cli/src/cli_commands.rs:467:26:
Mismatch between definition and access of `skip-records`. Could not downcast to u64, need to downcast to usize
```
Unfortunately `clap` is super sensitive to getting the exact type as the value converter produces.
Our commands are pretty complex, but we could try to migrate to `clippy derive` that avoids these kinds of issues.
=> Fix tail command cli parser regression

CHANGELOG.md, resources/schema.gql, src/adapter/graphql/src/mutations/flows_mut/dataset_flow_configs_mut.rs, src/adapter/graphql/tests/tests/test_gql_dataset_flow_configs.rs, src/domain/flow-system/src/aggregates/flow_configuration/flow_configuration.rs, src/domain/flow-system/src/services/flow_configuration/flow_configuration_service.rs, src/infra/flow-system-inmem/src/services/flow_configuration/flow_configuration_service_inmem.rs, src/infra/flow-system-inmem/tests/tests/test_flow_configuration_service_inmem.rs
Closes: #474 
New flow config APIs to pause/resume all dataset flows or flows of given type preserving the scheduling rule.
=> Flows: API to pause/resume dataset flows quickly

CHANGELOG.md, Cargo.lock, Cargo.toml, LICENSE.txt, resources/schema.gql, src/adapter/graphql/src/queries/datasets/dataset_flow_runs.rs, src/adapter/graphql/src/queries/tasks/tasks.rs, src/adapter/graphql/tests/tests/test_gql_dataset_flow_runs.rs, src/adapter/graphql/tests/tests/test_tasks.rs, src/domain/flow-system/src/entities/flow/flow_event.rs, src/domain/flow-system/src/entities/flow/flow_id.rs, src/domain/flow-system/src/repos/flow/flow_event_store.rs, src/domain/flow-system/src/services/flow/flow_service.rs, src/domain/task-system/src/repos/task_system_event_store.rs, src/domain/task-system/src/services/task_scheduler.rs, src/infra/flow-system-inmem/src/repos/flow/flow_event_store_inmem.rs, src/infra/flow-system-inmem/src/services/flow/flow_service_inmem.rs, src/infra/flow-system-inmem/tests/tests/mod.rs, src/infra/flow-system-inmem/tests/tests/test_flow_event_store_inmem.rs, src/infra/flow-system-inmem/tests/tests/test_flow_service_inmem.rs, src/infra/task-system-inmem/src/task_scheduler_inmem.rs, src/infra/task-system-inmem/src/task_system_event_store_inmem.rs, src/infra/task-system-inmem/tests/tests/test_event_store_inmem.rs
Closes: #476 
Server-side filtering of flows.
=> 476 flows provide api for server side filtering of flows that respects pagination as well

Cargo.toml, src/domain/core/src/services/verification_service.rs, src/infra/core/src/transform_service_impl.rs
Related issue: https://github.com/kamu-data/kamu-cli/issues/332
=> clippy: fix "pedantic::large_enum_variant" warnings

src/adapter/http/tests/tests/test_protocol_dataset_helpers.rs, src/app/cli/src/commands/ingest_command.rs, src/app/cli/src/commands/log_command.rs, src/app/cli/src/commands/pull_command.rs, src/app/cli/src/commands/push_command.rs, src/app/cli/tests/tests/test_system_info_command.rs, src/domain/core/src/services/pull_service.rs, src/domain/flow-system/src/entities/flow/flow_state.rs, src/domain/flow-system/src/entities/flow_configuration/flow_configuration_state.rs, src/domain/task-system/src/entities/task_state.rs, src/infra/core/src/ingest/polling_ingest_service_impl.rs, src/infra/core/tests/tests/ingest/test_writer.rs, src/infra/core/tests/tests/test_pull_service_impl.rs, src/infra/core/tests/tests/test_sync_service_impl.rs, src/infra/core/tests/tests/test_verification_service_impl.rs, src/infra/flow-system-inmem/tests/tests/test_flow_configuration_service_inmem.rs, src/infra/task-system-inmem/src/task_executor_inmem.rs, src/infra/task-system-inmem/tests/tests/test_task_scheduler_inmem.rs
Inspired by reading "Programming Rust" book.
=> Simlified structure patterns for irrelevant fields

.github/workflows/build.yaml, .github/workflows/release.yaml, CHANGELOG.md, src/infra/core/src/utils/docker_images.rs
Partially addresses: #246 
- General restructuring of `build` and `release` flows towards cleaner matrix workflows
- Adds testing on M1 processors (albeit omitting the dockerized tests)
- Adds `aarch64` release binaries for Linux and Mac
- Linux can be useful for AWS Graviton
=> Add arm64 targets to tests and release

.github/workflows/release-test-installer.yaml, installer/Makefile, installer/kamu-install.sh
Related to: #246
- Adds a workflow that will test our hosted installer script on linux (gnu / musl) and mac (intel / arm) 
- Workflow will automatically run after every `release`
=> Add installer test workflow

src/adapter/graphql/src/queries/datasets/metadata_chain.rs, src/adapter/http/src/simple_protocol/handlers.rs, src/adapter/http/src/smart_protocol/axum_server_pull_protocol.rs, src/adapter/http/src/smart_protocol/axum_server_push_protocol.rs, src/adapter/http/src/smart_protocol/ws_tungstenite_client.rs, src/adapter/http/tests/tests/test_routing.rs, src/app/cli/src/commands/list_command.rs, src/domain/core/src/entities/metadata_chain.rs, src/domain/core/src/repos/metadata_block_repository.rs, src/domain/core/src/utils/metadata_chain_comparator.rs, src/infra/core/src/repos/dataset_impl.rs, src/infra/core/src/repos/dataset_repository_local_fs.rs, src/infra/core/src/repos/dataset_repository_s3.rs, src/infra/core/src/repos/metadata_chain_impl.rs, src/infra/core/src/sync_service_impl.rs, src/infra/core/src/testing/dataset_data_helper.rs, src/infra/core/src/transform_service_impl.rs, src/infra/core/src/utils/simple_transfer_protocol.rs, src/infra/core/src/verification_service_impl.rs, src/infra/core/tests/tests/engine/test_engine_transform.rs, src/infra/core/tests/tests/ingest/test_writer.rs, src/infra/core/tests/tests/repos/test_dataset_repository_shared.rs, src/infra/core/tests/tests/repos/test_metadata_chain_impl.rs, src/infra/core/tests/tests/test_metadata_chain_comparator.rs, src/infra/core/tests/tests/test_reset_service_impl.rs, src/infra/core/tests/tests/test_transform_service_impl.rs, src/infra/ingest-datafusion/src/writer.rs
Related issue: https://github.com/kamu-data/kamu-cli/issues/389
Address 2 comments:
- Commit: [MetadataChain: rename get_ref() -> resolve_ref()](https://github.com/kamu-data/kamu-cli/commit/2ce073de7e834dee3f37d81d0dd1408d07156e43)
- Commit: [GetBlockError: move closer to MetadataBlockRepository](https://github.com/kamu-data/kamu-cli/commit/6cf0d945b0ee3b7ed8208563de094b6ad22e3fa3)
=> In-memory MetadataChain caching: follow-up changes

CHANGELOG.md, src/app/cli/src/commands/search_command.rs, src/app/cli/src/services/odf_server/access_token_registry_service.rs, src/domain/core/src/services/search_service.rs, src/infra/core/src/pull_service_impl.rs, src/infra/core/src/repos/dataset_factory_impl.rs, src/infra/core/src/search_service_impl.rs, src/infra/core/tests/tests/test_search_service_impl.rs
Closes: #508 
- Search service now supports `odf+http[s]` protocol
- As with other protocols the implementation is very crude - it's not using some established interfaces but reaches directly to GQL API
- this is a technical debt and we will clean it up in future, once #342 will bring more understanding on how remote registries will be organized
- Search results now include more details (number of blocks, records, estimated size)
- Search command output updated to avoid boilerplate
=> Support searching in ODF repos

CHANGELOG.md, resources/schema.gql, src/adapter/graphql/src/queries/flows/flow_event.rs, src/adapter/graphql/src/queries/flows/flow_start_condition.rs, src/adapter/graphql/src/scalars/flow_scalars.rs, src/adapter/graphql/tests/tests/test_gql_dataset_flow_runs.rs, src/domain/flow-system/src/aggregates/flow/flow.rs, src/domain/flow-system/src/entities/flow/flow_event.rs, src/domain/flow-system/src/entities/flow/flow_start_condition.rs, src/domain/flow-system/src/entities/flow/flow_state.rs, src/domain/flow-system/src/entities/flow/flow_status.rs, src/domain/flow-system/src/services/flow/flow_service_test_driver.rs, src/infra/flow-system-inmem/src/services/flow/flow_service_inmem.rs, src/infra/flow-system-inmem/src/services/flow/flow_time_wheel.rs, src/infra/flow-system-inmem/tests/tests/test_flow_event_store_inmem.rs, src/infra/flow-system-inmem/tests/tests/test_flow_service_inmem.rs, src/infra/flow-system-inmem/tests/tests/utils/flow_system_test_listener.rs
Closes: #516
-2 flow statuses (-Queued, -Scheduled)
+2 flow conditoins (Schedule, Executor).
=> 516 flows simplify waiting statuses and replace the differentiation on extended start conditions

.github/workflows/build.yaml, CHANGELOG.md, Cargo.lock, DEVELOPER.md, Makefile, src/adapter/auth-oso/Cargo.toml, src/adapter/flight-sql/Cargo.toml, src/adapter/graphql/Cargo.toml, src/adapter/http/Cargo.toml, src/adapter/oauth/Cargo.toml, src/app/cli/Cargo.toml, src/domain/opendatafabric/Cargo.toml, src/infra/core/Cargo.toml, src/infra/flow-system-inmem/Cargo.toml, src/infra/ingest-datafusion/Cargo.toml, src/infra/task-system-inmem/Cargo.toml, src/utils/container-runtime/Cargo.toml, src/utils/data-utils/Cargo.toml, src/utils/event-bus/Cargo.toml, src/utils/event-sourcing/Cargo.toml, src/utils/internal-error/Cargo.toml, src/utils/repo-tools/Cargo.toml, src/utils/tracing-perfetto/Cargo.toml
Added `cargo-udeps` step into `make lint` and GH build action (Lint dependencies).
Added GH action to quickly install latest version of `binstall` so that `udeps` and `deny` are quickly installed.
Cleaned all unused dependencies in our TOML.
=> Utilized `cargo-udeps` application to detect unused dependencies

CHANGELOG.md, src/adapter/graphql/src/scalars/pagination.rs, src/adapter/graphql/tests/tests/test_gql_search.rs
Closes: [Division by zero error in GQL API](https://github.com/kamu-data/kamu-cli/issues/520)
=> Fix zero value per page pagination

CHANGELOG.md, Cargo.lock, Cargo.toml, Makefile, src/adapter/graphql/src/queries/datasets/datasets.rs, src/adapter/odata/Cargo.toml, src/adapter/odata/src/context.rs, src/adapter/odata/src/handler.rs, src/adapter/odata/src/lib.rs, src/adapter/odata/src/router.rs, src/adapter/odata/tests/mod.rs, src/adapter/odata/tests/tests/mod.rs, src/adapter/odata/tests/tests/test_api_server.rs, src/adapter/odata/tests/tests/test_handlers.rs, src/app/cli/Cargo.toml, src/app/cli/src/commands/list_command.rs, src/app/cli/src/commands/pull_command.rs, src/app/cli/src/commands/push_command.rs, src/app/cli/src/explore/api_server.rs, src/app/cli/src/explore/web_ui_server.rs, src/domain/core/src/repos/dataset_repository.rs, src/domain/core/src/services/query_service.rs, src/infra/core/src/pull_service_impl.rs, src/infra/core/src/query_service_impl.rs, src/infra/core/src/repos/dataset_repository_local_fs.rs, src/infra/core/src/repos/dataset_repository_s3.rs, src/infra/core/src/utils/datasets_filtering.rs, src/infra/core/tests/tests/repos/test_dataset_repository_shared.rs, src/infra/core/tests/tests/test_datasets_filtering.rs
Closes: https://github.com/kamu-data/kamu-node/issues/54
Not proud of this code:
- it's missing a lot of error handling
- it does not enforce permissions on the top level
But this is a stop-gap measure to unblock customer integration. We can improve it as we go if there will be further demand for OData.
=> Add OData protocol adapter

CHANGELOG.md, src/infra/core/src/repos/dataset_repository_s3.rs, src/infra/core/tests/tests/repos/test_dataset_repository_s3.rs
Fixes a bug when handle assigned to the dataset during its creation in a multi-tenant S3 repo had an empty account name.
=> Ensure handle has correct alias after dataset creation

CHANGELOG.md, src/infra/core/src/repos/dataset_repository_s3.rs, src/infra/core/src/repos/object_repository_caching_local_fs.rs
- S3 Repo: Ignore dataset entries without a valid alias and leave them to be cleaned up by GC
- Caching object repo: Ensure directory exists before writing objects
=> S3 tolerance and caching fix

CHANGELOG.md, Cargo.lock, src/adapter/odata/Cargo.toml, src/adapter/odata/src/context.rs, src/adapter/odata/src/handler.rs, src/adapter/odata/tests/tests/test_handlers.rs
- OData API now supports querying by collection ID/key (e.g. `account/covid.cases(123)`)
- added env var to make the default number of entries per page configurable
=> OData: allow queries by id/offset

CHANGELOG.md, examples/covid/canada.case-details.yaml, examples/covid/canada.daily-cases.yaml, examples/covid/ontario.case-details.yaml, examples/covid/quebec.case-details.yaml, examples/leaderboard/data/1.ndjson, examples/leaderboard/data/2.ndjson, examples/leaderboard/data/3.ndjson, examples/leaderboard/init.sh, examples/leaderboard/leaderboard.yaml, examples/leaderboard/player-scores.yaml, src/app/cli/src/app.rs, src/app/cli/src/commands/pull_images_command.rs, src/app/cli/src/services/config/models.rs, src/infra/core/src/engine/engine_provisioner_local.rs, src/infra/core/src/utils/docker_images.rs, src/infra/core/tests/tests/engine/test_engine_transform.rs, src/infra/core/tests/tests/test_setup.rs
Related to: #456
- Added RW engine
- Using newer faster version of Flink as well
- Updated `covid` example to use only datafusion + risingwave for great performance
- New `leaderboard` example showcasing Top-N query, that I will document soon in our docs
=> Add RisingWave engine

CHANGELOG.md, resources/schema.gql, src/adapter/graphql/src/mutations/flows_mut/dataset_flow_configs_mut.rs
Split results for different(`setFlowConfigResult`, `setFlowBatchingConfigResult`, `setFlowCompactingConfigResult`) config mutations
=> Split results for different config mutations

CHANGELOG.md, resources/cli-reference.md, resources/schema.gql, src/adapter/graphql/src/queries/flows/flow.rs, src/adapter/graphql/src/queries/flows/flow_outcome.rs, src/adapter/graphql/tests/tests/test_gql_dataset_flow_runs.rs, src/app/cli/src/cli_parser.rs, src/app/cli/src/commands/compact_command.rs, src/infra/flow-system-inmem/src/services/flow/flow_service_inmem.rs
- Fix the instant run of `ExecuteTransform` flow after the successful finish of `HardCompacting` flow 
- Rename `compaction` -> `compacting` in CLI reference
- Add new error type `FlowDatasetCompactedFailedError`
=> Fix instant run of transform flow after compacting

src/adapter/graphql/src/mutations/flows_mut/dataset_flow_configs_mut.rs, src/adapter/graphql/tests/tests/test_gql_dataset_flow_configs.rs, src/domain/task-system/services/src/task_executor_impl.rs, src/infra/core/src/compacting_service_impl.rs
Fix regressing that gql config setting was not activated automatically.
In addition, added logs for compacting failure
=> Activate compacting config by default

CHANGELOG.md, src/app/cli/src/cli_commands.rs, src/app/cli/src/commands/system_diagnose_command.rs
Closes: [System diagnose command crashes when not in workspace](https://github.com/kamu-data/kamu-cli/issues/610)
=> Fix crash diagnose command not in workspace

CHANGELOG.md, src/infra/core/src/compacting_service_impl.rs, src/infra/core/src/ingest/ingest_common.rs, src/infra/core/src/ingest/mod.rs, src/infra/core/tests/tests/test_compact_service_impl.rs
Fix issue with compacting of s3 stored datasets
=> Fix s3 compacting

CHANGELOG.md, src/app/cli/src/cli_parser.rs, src/app/cli/tests/tests/mod.rs, src/app/cli/tests/tests/test_repository_alias_commands.rs, src/app/cli/tests/utils/kamu.rs
Closes: [
Regression: Repo alias commands fail](https://github.com/kamu-data/kamu-cli/issues/608)
Fix Repo alias command crash regression
Added integration test to cover regression in the future
=> Fix repo command crash

CHANGELOG.md, Cargo.lock, Cargo.toml, LICENSE.txt, src/domain/accounts/domain/src/services/authentication_config.rs
Related issue: https://github.com/kamu-data/kamu-node/issues/45
=> JwtAuthenticationConfig::new(): make "jwt_secret" as optional for `kamu-node`

CHANGELOG.md, src/app/cli/src/commands/ingest_command.rs
Closes: [Ingest command panic during ingesting derived dataset](https://github.com/kamu-data/kamu-cli/issues/627)
Fix panic while performing data ingestion in the derived dataset.
=> Fix panic while ingesting data in derived dataset

CHANGELOG.md, resources/cli-reference.md, src/app/cli/src/cli_commands.rs, src/app/cli/src/cli_parser.rs, src/app/cli/src/commands/compact_command.rs, src/domain/core/src/services/compacting_service.rs, src/domain/task-system/services/src/task_executor_impl.rs, src/infra/core/src/compacting_service_impl.rs, src/infra/core/src/repos/dataset_impl.rs, src/infra/core/tests/tests/test_compact_service_impl.rs
Closes: [Add --keep-metadata-only flag to compact command](https://github.com/kamu-data/kamu-cli/issues/625)
Extend compact command with new flag `--keep-metadata-only` which remove all data(`AddData`/`ExecuteTransfrom`) blocks
=> Add keep-metadata-only flag to compact command

CHANGELOG.md, Cargo.lock, examples/mqtt/pub.py, examples/mqtt/requirements.txt, examples/mqtt/temp.yaml, resources/schema.gql, src/adapter/graphql/src/scalars/odf_generated.rs, src/domain/opendatafabric/schemas/odf.fbs, src/domain/opendatafabric/src/dtos/dtos_dyntraits_generated.rs, src/domain/opendatafabric/src/dtos/dtos_generated.rs, src/domain/opendatafabric/src/serde/flatbuffers/convertors_generated.rs, src/domain/opendatafabric/src/serde/flatbuffers/proxies_generated.rs, src/domain/opendatafabric/src/serde/yaml/derivations_generated.rs, src/infra/core/Cargo.toml, src/infra/core/src/ingest/fetch_service.rs, src/infra/core/src/ingest/polling_ingest_service_impl.rs, src/infra/core/src/utils/docker_images.rs, src/infra/core/tests/tests/ingest/test_fetch.rs, src/infra/core/tests/tests/test_setup.rs, src/infra/core/tests/utils/mod.rs, src/infra/core/tests/utils/mqtt_broker.rs
Relates to: #368 
This PR allows to define a dataset like this:
```yaml
kind: DatasetSnapshot
version: 1
content:
name: temp
kind: Root
metadata:
- kind: SetPollingSource
fetch:
kind: mqtt
host: test.mosquitto.org
port: 1883
topics:
- path: dev.kamu.example.mqtt.temp
qos: AtMostOnce
read:
kind: NdJson
...
```
In this case `kamu-cli` will act as an MQTT **client**, subscribing to some topic(s).
Upon `kamu pull` it will connect to the MQTT broker and either:
- get nothing and exit after some configurable timeout
- get "retained" MQTT event - e.g. last temperature measurement that broker stores and sends upon subscription
- get a history of events it missed if MQTT QoS level is == `AtLeastOnce` or `ExactlyOnce` which makes broker buffer events for some time when subscriber is offline (the …
=> Add initial MQTT support

CHANGELOG.md, resources/schema.gql, src/adapter/graphql/src/mutations/flows_mut/dataset_flow_configs_mut.rs, src/adapter/graphql/src/queries/flows/flow_config_snapshot.rs, src/adapter/graphql/src/scalars/flow_configuration.rs, src/adapter/graphql/tests/tests/test_gql_dataset_flow_configs.rs, src/adapter/graphql/tests/tests/test_gql_dataset_flow_runs.rs, src/domain/flow-system/domain/src/entities/shared/compacting_rule.rs, src/domain/flow-system/services/src/flow/flow_service_impl.rs, src/domain/flow-system/services/tests/tests/test_flow_service_impl.rs
Closes: https://github.com/kamu-data/kamu-cli/issues/643
=> Extend compacting config with recursive flag

CHANGELOG.md, resources/schema.gql, src/adapter/graphql/src/mutations/flows_mut/account_flow_configs_mut.rs, src/adapter/graphql/src/queries/accounts/account_flow_configs.rs, src/adapter/graphql/src/queries/accounts/account_flows.rs, src/adapter/graphql/src/queries/accounts/mod.rs, src/adapter/graphql/tests/tests/test_gql_account_flow_configs.rs, src/domain/flow-system/domain/src/services/flow_configuration/flow_configuration_service.rs, src/domain/flow-system/services/src/flow_configuration/flow_configuration_service_impl.rs
Closes: https://github.com/kamu-data/kamu-cli/issues/652
=> Add new allPaused method in AccountFlowConfigs API

CHANGELOG.md, resources/cli-reference.md, src/adapter/http/tests/harness/client_side_harness.rs, src/app/cli/src/cli_commands.rs, src/app/cli/src/cli_parser.rs, src/app/cli/src/commands/compact_command.rs, src/app/cli/src/commands/pull_command.rs, src/domain/core/src/services/compacting_service.rs, src/domain/core/src/services/pull_service.rs, src/domain/core/src/services/transform_service.rs, src/infra/core/src/compacting_service_impl.rs, src/infra/core/src/pull_service_impl.rs, src/infra/core/src/testing/mock_transform_service.rs, src/infra/core/src/transform_service_impl.rs, src/infra/core/tests/tests/engine/test_engine_io.rs, src/infra/core/tests/tests/engine/test_engine_transform.rs, src/infra/core/tests/tests/test_compact_service_impl.rs, src/infra/core/tests/tests/test_pull_service_impl.rs, src/infra/core/tests/tests/test_transform_service_impl.rs, src/infra/core/tests/tests/test_verification_service_impl.rs, src/infra/core/tests/utils/mock_engine_provisioner.rs
Closes: https://github.com/kamu-data/kamu-cli/issues/644
=> Add reset derivative flag to pull command

CHANGELOG.md, Cargo.lock, src/adapter/graphql/src/queries/data.rs, src/adapter/http/Cargo.toml, src/adapter/http/src/data/query_handler.rs, src/adapter/http/src/data/router.rs, src/adapter/http/src/data/tail_handler.rs, src/adapter/http/tests/tests/test_data_query.rs, src/app/cli/src/commands/sql_shell_command.rs, src/domain/core/src/services/query_service.rs, src/infra/core/Cargo.toml, src/infra/core/src/query/mod.rs, src/infra/core/src/query_service_impl.rs, src/infra/core/tests/tests/test_query_service_impl.rs, src/utils/data-utils/src/data/hash.rs
- The `/query` REST API endpoint now supports:
- POST requests with all parameters being passed via body
- Specifying schema format
- Specifying `aliases` to associate table names with specific dataset IDs
- Returning and providing state information to achieve full reproducibility of queries
Example oracle interaction will now look like this:
POST request:
```json
{
"query": "select offset, city, population from foo order by offset desc",
"dataFormat": "JsonAoA",
"aliases": [{
"alias": "foo",
"id": "did:odf:fed01df230b49615d175307d580c33d6fda61fc7b9aec91df0f5c1a5ebe3b8cbfee02"
}]
}
```
Response:
```json
{
"data": [[1, "B", 200], [0, "A", 100]],
"schema": "...",
"resultHash": "f9680c001200b3483eecc3d5c6b50ee6b8cba11b51c08f89ea1f53d3a334c743199f5fe656e",
"state": {
"inputs": [{
"id": …
```
=> Add query reproducibility and aliases support

CHANGELOG.md, src/adapter/http/src/data/query_handler.rs, src/adapter/http/tests/tests/test_data_query.rs, src/infra/core/tests/tests/test_query_service_impl.rs
The `/query` REST API endpoint will:
- return `404 Not Found` on not found datasets
- return `400 Bad Request` on invalid SQL
- return `422 Unprocessable Content` on unrecognized request body fields
=> Improve REST query error handling

src/adapter/graphql/tests/tests/test_gql_metadata.rs, src/adapter/http/src/upload/upload_service_local.rs, src/adapter/http/tests/harness/client_side_harness.rs, src/adapter/http/tests/harness/server_side_local_fs_harness.rs, src/adapter/http/tests/harness/server_side_s3_harness.rs, src/adapter/http/tests/tests/test_data_ingest.rs, src/adapter/http/tests/tests/test_data_query.rs, src/adapter/http/tests/tests/test_upload_local.rs, src/adapter/odata/tests/tests/test_handlers.rs, src/app/cli/src/app.rs, src/domain/core/src/lib.rs, src/domain/core/src/utils/mod.rs, src/domain/core/src/utils/paths.rs, src/infra/core/src/compacting_service_impl.rs, src/infra/core/src/engine/engine_odf.rs, src/infra/core/src/engine/engine_provisioner_local.rs, src/infra/core/src/ingest/fetch_service.rs, src/infra/core/src/ingest/polling_ingest_service_impl.rs, src/infra/core/src/ingest/push_ingest_service_impl.rs, src/infra/core/src/remote_repository_registry_impl.rs, src/infra/core/tests/benches/parallel_simple_transfer_protocol.rs, src/infra/core/tests/tests/engine/test_engine_io.rs, src/infra/core/tests/tests/engine/test_engine_transform.rs, src/infra/core/tests/tests/ingest/test_fetch.rs, src/infra/core/tests/tests/ingest/test_polling_ingest.rs, src/infra/core/tests/tests/ingest/test_push_ingest.rs, src/infra/core/tests/tests/test_compact_service_impl.rs, src/infra/core/tests/tests/test_sync_service_impl.rs, src/infra/core/tests/tests/test_transform_service_impl.rs
Simplifies dependency injection configuration by wrapping run/cache directories into new types.
This way they don't have to be passed into builders using e.g. `with_run_dir(..)` calls, and thus most types can be added without going through a builder interface, which in its turn avoids the need for binding them to interfaces explicitly.
This removes a ton of boilerplate.
=> Newtypes for common paths

CHANGELOG.md, src/adapter/graphql/src/queries/data.rs, src/adapter/graphql/src/queries/datasets/dataset_data.rs, src/adapter/http/src/data/query_handler.rs, src/adapter/http/src/data/tail_handler.rs, src/adapter/odata/src/context.rs, src/adapter/odata/tests/tests/test_handlers.rs, src/app/cli/src/commands/sql_shell_command.rs, src/app/cli/src/commands/tail_command.rs, src/domain/core/src/services/query_service.rs, src/infra/core/src/query/mod.rs, src/infra/core/src/query_service_impl.rs, src/infra/core/tests/tests/test_query_service_impl.rs
In this PR:
- We avoid the need for having `SessionState` in `KamuTable`
- This is possible because `KamuTable` only needs the state to call `resolve_schema()` that may need to infer the schema from files, bun in our case we already know exactly what the schema is
- This in turn avoids the need to have a strong reference for `SessionContext` somewhere and thus the need for `DataFrameWithContext` struct, so all `QueryService` API changes can be reverted
=> Avoid referencing SessionState in KamuTable

.env.example, CHANGELOG.md, Cargo.lock, Cargo.toml, LICENSE.txt, src/adapter/http/src/upload/upload_service.rs, src/adapter/http/src/upload/upload_service_local.rs, src/adapter/http/src/upload/upload_service_s3.rs, src/adapter/http/tests/tests/test_data_ingest.rs, src/adapter/http/tests/tests/test_upload_local.rs, src/adapter/http/tests/tests/test_upload_s3.rs, src/app/cli/src/app.rs, src/app/cli/src/cli_commands.rs, src/app/cli/src/commands/system_api_server_run_command.rs, src/app/cli/src/commands/ui_command.rs, src/app/cli/src/explore/api_server.rs, src/app/cli/src/explore/web_ui_server.rs, src/domain/core/src/services/server_url_config.rs
Fixed support of  ingestion via file upload in `kamu ui` mode + `kamu system api-server` mode with custom HTTP port.
Fixed broken transaction in `kamu ui` mode
=> Fixed support of  ingestion via file upload in `kamu ui` mode

CHANGELOG.md, Cargo.lock, Cargo.toml, LICENSE.txt, resources/cli-reference.md, src/app/cli/src/cli_commands.rs, src/app/cli/src/cli_parser.rs, src/app/cli/src/commands/system_api_server_run_command.rs, src/app/cli/src/explore/api_server.rs, src/domain/core/src/services/server_url_config.rs
Closes: 
- https://github.com/kamu-data/kamu-cli/issues/686
- `kamu system api-server`: Added the option of overriding the base URL in the API with `--external-address`. 
Can be handy when launching inside a container
=> Added the option of overriding the base URL in the API with `--external-address`

CHANGELOG.md, src/adapter/graphql/tests/tests/test_gql_data.rs, src/adapter/http/src/data/query_handler.rs, src/adapter/http/tests/tests/test_data_query.rs, src/infra/core/src/query_service_impl.rs
Closes: https://github.com/kamu-data/kamu-node/issues/92
My previous changes in #668 introduced a regression where unparsable SQL was causing internal errors.
This PR fixes it and covers with tests.
=> Handle unparsable SQL error

.config/nextest.toml, CHANGELOG.md, src/app/cli/src/app.rs, src/app/cli/src/cli_commands.rs, src/app/cli/src/cli_parser.rs, src/app/cli/src/commands/system_api_server_run_command.rs, src/app/cli/src/explore/api_server.rs, src/app/cli/src/services/config/models.rs, src/app/cli/src/testing/kamu.rs, src/e2e/app/cli/common/src/e2e_harness.rs, src/e2e/app/cli/common/src/e2e_test.rs, src/e2e/app/cli/common/src/lib.rs, src/infra/core/src/repos/dataset_factory_impl.rs, src/utils/event-sourcing/src/aggregate.rs
Closes: #666
Depend on: 
- https://github.com/kamu-data/kamu-cli/pull/712
- E2E: unblocked parallel run for tests
- Fixed base_url calculation for random port
- Minor corrections to references in generated code documentation
=> E2E: Parallel running of tests

CHANGELOG.md, resources/schema.gql, src/adapter/graphql/src/mutations/flows_mut/dataset_flow_configs_mut.rs, src/adapter/graphql/src/scalars/flow_configuration.rs, src/adapter/graphql/tests/tests/test_gql_dataset_flow_configs.rs, src/adapter/graphql/tests/tests/test_gql_dataset_flow_runs.rs, src/domain/flow-system/domain/src/entities/shared/compaction_rule.rs, src/domain/flow-system/services/src/flow/flow_service_impl.rs, src/domain/flow-system/services/tests/tests/test_flow_service_impl.rs
Closes: https://github.com/kamu-data/kamu-cli/issues/740
=> Add full compaction recursive flag

CHANGELOG.md, resources/cli-reference.md, src/app/cli/src/cli_commands.rs, src/app/cli/src/cli_parser.rs, src/app/cli/src/commands/add_command.rs
Allows overriding a name on add:
```sh
kamu add my-dataset.yaml --name my-dataset-with-a-different-name
```
=> Add name override parameter to add command

.config/nextest.toml, CHANGELOG.md, src/app/cli/src/app.rs, src/e2e/app/cli/common-macros/src/lib.rs, src/utils/kamu-cli-puppet/src/kamu_cli_puppet.rs
Related issue: https://github.com/kamu-data/kamu-cli/issues/718
- E2E: modify a workaround for MySQL tests
=> E2E: modify a workaround for MySQL tests

CHANGELOG.md, Cargo.lock, src/adapter/http/Cargo.toml, src/adapter/http/src/data/ingest_handler.rs, src/adapter/http/src/upload/upload_handler.rs, src/adapter/http/src/upload/upload_service.rs, src/adapter/http/src/upload/upload_service_local.rs, src/adapter/http/src/upload/upload_service_s3.rs, src/adapter/http/tests/tests/test_data_ingest.rs, src/adapter/http/tests/tests/test_upload_local.rs, src/adapter/http/tests/tests/test_upload_s3.rs, src/domain/core/src/services/ingest/data_format_registry.rs, src/infra/core/src/ingest/data_format_registry_impl.rs
Closes: kamu-data/kamu-node#98
When uploading a file via Web UI the media type is read in TypeScript through standard library and passed unchecked into query parameter. On `.ndjson` files the file type is empty and hits the backend as `&contentType=`.
* Refactoring of `UploadToken` serde to prevent empty strings like `content_type: Some(MediaType(""))` from getting into core services
* If content type is not specified - the handler will try to deduce it from file extension
=> Ingest from file upload detects media type from extension

CHANGELOG.md, src/app/cli/src/app.rs, src/app/cli/src/services/config/models.rs, src/infra/core/src/ingest/fetch_service.rs, src/infra/core/tests/tests/engine/test_engine_io.rs, src/infra/core/tests/tests/ingest/test_fetch.rs
=> Add User-Agent header and externalize HTTP config

src/adapter/http/src/data/ingest_handler.rs, src/app/cli/src/commands/ingest_command.rs, src/app/cli/src/commands/pull_command.rs, src/domain/core/src/services/ingest/polling_ingest_service.rs, src/domain/core/src/services/ingest/push_ingest_service.rs, src/infra/core/src/ingest/ingest_common.rs, src/infra/core/src/ingest/polling_ingest_service_impl.rs, src/infra/core/src/ingest/push_ingest_service_impl.rs, src/infra/core/tests/tests/ingest/test_push_ingest.rs
Closes: #790
If user does not declare `read` schema or `preprocess` step (which is always the case when ingesting data from a file upload) we apply the following new inference rules:
- if `event_time` column is present - we will try to coerce it into a timestamp
- strings will be parsed as RFC3339 date-times
- integers will be treated as UNIX timestamps in seconds
- if any of the columns conflicts with system column - it will get renamed with an underscore prefix
While I like being strict about names and types, I think this should improve the overall user experience.
will add a paragraph to public docs if this gets merged
=> Auto rename and coerce columns on ingest

CHANGELOG.md, Cargo.lock, Cargo.toml, LICENSE.txt, deny.toml
- If a polling/push source does not declare a `read` schema or a `preprocess` step (which is the case when ingesting data from a file upload) we apply the following new inference rules:
- If `event_time` column is present - we will try to coerce it into a timestamp:
- strings will be parsed as RFC3339 date-times
- integers will be treated as UNIX timestamps in seconds
- Columns with names that conflict with system columns will get renamed
- All tests related to databases use the `database_transactional_test` macro
- Some skipped tests will now also be run
- Access token with duplicate names can be created if such name exists but was revoked (now for MySQL as well)
- :warning: Updated `sqlx` crate to address [RUSTSEC-2024-0363](https://rustsec.org/advisories/RUSTSEC-2024-0363)
- Derivative …
=> Release 0.198.0 (focus on the "address RUSTSEC-2024-0363")

CHANGELOG.md, Cargo.lock, Cargo.toml, LICENSE.txt
- Private Datasets, ReBAC integration: 
- ReBAC properties update based on `DatasetLifecycleMessage`'s:
- `kamu add`: added hidden `--visibility private|public` argument, assumed to be used in multi-tenant case
- GQL: `DatasetsMut`:
- `createEmpty()`: added optional `datasetVisibility` argument
- `createFromSnapshot()`: added optional `datasetVisibility` argument
=> Release (patch): 0.198.1

src/domain/core/src/services/ingest/polling_ingest_service.rs, src/domain/datasets/domain/src/entities/dataset_env_var.rs, src/domain/datasets/domain/src/services/dataset_key_value_service.rs, src/domain/datasets/services/src/dataset_key_value_service_impl.rs, src/domain/datasets/services/src/dataset_key_value_service_sys_env.rs, src/infra/core/src/ingest/fetch_service/container.rs, src/infra/core/src/ingest/fetch_service/evm.rs, src/infra/core/src/ingest/fetch_service/mod.rs, src/infra/core/src/ingest/fetch_service/mqtt.rs, src/infra/core/tests/tests/ingest/test_fetch.rs
Note: this is based off my refactoring branch
Initially I was just going to support templating in containerized source's env vars, but I realized that the container fetch was not converted to use the new vars service and was remaining a severe security threat as it continued to pull data from system env.
The fix took me longer than expected as I was fighting the API.
Will leave some inline comments to explain.
=> Use dataset env vars in container sources

images/Makefile, images/demo/Makefile, src/infra/core/src/utils/docker_images.rs
This PR updates the image versions and also confirms that the following commands are executed:
- https://github.com/kamu-data/kamu-cli/pkgs/container/jupyter/266143027?tag=0.6.3
- https://github.com/kamu-data/kamu-cli/pkgs/container/kamu-cli-demo-jupyter/266147557?tag=0.16.2
- https://github.com/kamu-data/kamu-cli/pkgs/container/kamu-cli-demo-minio/266162771?tag=0.16.2
=> Jupyter images version bump

CHANGELOG.md, src/adapter/graphql/src/mutations/flows_mut/dataset_flow_configs_mut.rs, src/adapter/graphql/src/mutations/flows_mut/dataset_flow_runs_mut.rs, src/adapter/graphql/src/mutations/flows_mut/flows_mut_utils.rs, src/adapter/graphql/src/scalars/flow_configuration.rs, src/adapter/graphql/tests/tests/test_gql_dataset_flow_configs.rs, src/domain/flow-system/domain/src/entities/shared/flow_type.rs
=> Expose metadata only compaction for derived datasets

CHANGELOG.md, resources/schema.gql, src/adapter/graphql/src/queries/flows/flow_outcome.rs, src/adapter/graphql/tests/tests/test_gql_account_flow_configs.rs, src/adapter/graphql/tests/tests/test_gql_dataset_flow_runs.rs, src/domain/core/src/services/transform_service.rs, src/domain/flow-system/domain/src/entities/flow/flow_outcome.rs, src/domain/task-system/domain/src/entities/task_status.rs, src/domain/task-system/services/src/task_logical_plan_runner_impl.rs, src/infra/core/src/transform_service_impl.rs, src/infra/core/tests/tests/test_transform_service_impl.rs
Closes: #820
UI update required, GraphQL schema has renamings.
=> Correct dataset id is sent when input dataset was compacted before transform

CHANGELOG.md, src/adapter/http/src/upload/upload_service_local.rs, src/adapter/odata/src/context.rs, src/domain/auth-rebac/services/src/multi_tenant_rebac_dataset_lifecycle_message_consumer.rs, src/domain/flow-system/services/src/flow/flow_executor_impl.rs, src/domain/flow-system/services/src/flow/flow_time_wheel_service_impl.rs, src/domain/flow-system/services/src/flow_configuration/flow_configuration_service_impl.rs, src/domain/task-system/services/src/task_executor_impl.rs, src/infra/accounts/mysql/src/repos/mysql_account_repository.rs, src/infra/accounts/postgres/src/repos/postgres_account_repository.rs, src/infra/accounts/sqlite/src/repos/sqlite_account_repository.rs, src/infra/core/src/dataset_ownership_service_inmem.rs, src/infra/core/src/dependency_graph_service_inmem.rs, src/infra/core/src/ingest/polling_ingest_service_impl.rs, src/infra/core/src/ingest/push_ingest_service_impl.rs, src/infra/core/src/query_service_impl.rs, src/infra/core/src/repos/object_store_builder_s3.rs, src/infra/core/src/transform_service_impl.rs, src/utils/messaging-outbox/src/services/implementation/outbox_immediate_impl.rs, src/utils/messaging-outbox/src/services/outbox_transactional_processor.rs
Main loops of `Outbox` and `TaskExecutor` are not interrupted in case a particular message/task fails with an internal error.
The error is logged instead among with contextual information, and the execution loop continues.
=> Improved stability of Outbox and TaskExecutor

CHANGELOG.md, Cargo.lock, Cargo.toml, deny.toml, resources/cli-reference.md, src/app/cli/Cargo.toml, src/app/cli/src/app.rs, src/app/cli/src/cli.rs, src/app/cli/src/explore/api_server.rs, src/app/cli/src/explore/web_ui_server.rs, src/app/cli/src/output/output_config.rs, src/domain/task-system/services/Cargo.toml, src/domain/task-system/services/src/task_executor_impl.rs, src/utils/database-common/src/transactions/db_transaction_manager.rs, src/utils/messaging-outbox/Cargo.toml, src/utils/messaging-outbox/src/services/outbox_transactional_processor.rs, src/utils/messaging-outbox/tests/tests/test_outbox_transactional_processor.rs, src/utils/observability/Cargo.toml, src/utils/observability/src/axum.rs, src/utils/observability/src/config.rs, src/utils/observability/src/health.rs, src/utils/observability/src/init.rs, src/utils/observability/src/lib.rs, src/utils/observability/src/metrics.rs, src/utils/observability/src/tracing.rs
Closes https://github.com/kamu-data/kamu-node/issues/130
- Moving `observability` crate from `kamu-node` down into `kamu-cli`
- Improved DI <> Prometheus integration
- Switched `kamu system api-server` to use same tracing middlewares as `kamu-node` and expose health and metrics endpoints
- Added `outbox_failed_consumers` metric
Example:
```
$ kamu -vv --metrics system api-server --http-port 8899
$ xh GET "http://localhost:8899/system/metrics"
HTTP/1.1 200 OK
Content-Length: 855
Content-Type: text/plain; charset=utf-8
Date: Fri, 13 Sep 2024 01:59:15 GMT
outbox_failed_consumers{consumer="dev.kamu.domain.flow-system.FlowConfigurationService",producer="dev.kamu.domain.core.services.DatasetService"} 0
outbox_failed_consumers{consumer="dev.kamu.domain.flow-system.FlowExecutor",producer="dev.kamu …
```
=> Integrate prometheus metrics

CHANGELOG.md, src/adapter/graphql/tests/tests/test_gql_dataset_flow_runs.rs, src/domain/flow-system/domain/src/entities/flow/flow_state.rs
=> kamu-cli#834: failed flows should still propagate `finishedAt` time

CHANGELOG.md, src/utils/data-utils/src/data/format/csv.rs, src/utils/data-utils/src/data/format/json.rs, src/utils/data-utils/src/data/format/mod.rs, src/utils/data-utils/src/data/format/text.rs, src/utils/data-utils/src/data/format/traits.rs
Adds JSON encoding of lists and structs (as required for a customer dataset).
=> JSON encoding of lists and structs

CHANGELOG.md, src/app/cli/src/commands/delete_command.rs, src/domain/core/src/services/dependency_graph_service.rs, src/infra/core/src/dependency_graph_service_inmem.rs, src/infra/core/tests/tests/test_dependency_graph_inmem.rs
Closes: #843
`kamu delete` command will respect dependency graph ordering allowing to delete multiple datasets without encountering dangling reference errors
=> Delete respects graph order

CHANGELOG.md, Cargo.lock, Cargo.toml, LICENSE.txt, src/app/cli/src/app.rs, src/app/cli/src/database.rs, src/e2e/app/cli/inmem/tests/tests/commands/test_init_command.rs, src/e2e/app/cli/repo-tests/src/commands/test_init_command.rs
Closes: https://github.com/kamu-data/kamu-cli/issues/853
- `kamu init`: fixed regression in case of using `exists_ok` flag... finally
=> kamu init: fixed regression in case of using exists_ok flag + Release (patch): 0.204.3

CHANGELOG.md, resources/cli-reference.md, src/app/cli/src/app.rs, src/app/cli/src/cli.rs, src/app/cli/src/cli_commands.rs, src/app/cli/src/commands/add_command.rs, src/app/cli/src/commands/alias_delete_command.rs, src/app/cli/src/commands/common.rs, src/app/cli/src/commands/compact_command.rs, src/app/cli/src/commands/delete_command.rs, src/app/cli/src/commands/repository_add_command.rs, src/app/cli/src/commands/repository_delete_command.rs, src/app/cli/src/commands/reset_command.rs, src/app/cli/src/output/interact.rs, src/app/cli/src/output/mod.rs
- Make `--yes / -y` flag global
- Introduces `Interact` object that can be used to ask for action confirmations
- In future I'd like all messages, progress bars etc. to go through this object so we could automatically adjust the output based on verbosity level and whether we're under TTY, instead of individual commands handling flags like `verbose` and `quiet`
- Fixes a parsing error in SystemCompact command (turns out you still can have dynamic errors with clap derive)
- Adds confirmation to `system compact` command
- Allows `system compact` process multiple datasets at once
=> Generalize CLI confirmations

CHANGELOG.md, examples/covid/init-odf.sh, src/app/cli/src/commands/alias_list_command.rs, src/e2e/app/cli/repo-tests/src/commands/test_repo_alias_command.rs, src/utils/kamu-cli-puppet/src/kamu_cli_puppet_ext.rs
Closes: #751
This is a continuation of PR #866 by @demusdev
I have tested the changes and added just one commit to convert our E2E test from manual CSV parser to serde, so we could fully address the scope of #751 and close it.
=> Extend output formats of `repo alias list` command (cont.)

CHANGELOG.md, Cargo.lock, Cargo.toml, LICENSE.txt, src/app/cli/src/output/interact.rs
Closes: #880 
- `--yes / -y` flag: fixed when working from a TTY
- partially added in another PR (https://github.com/kamu-data/kamu-cli/pull/878)
=> Release (patch) `0.204.5`: fix `--yes / -y` flag: fixed when working from a TTY

CHANGELOG.md, images/kamu-base-with-data-mt/extra/.kamuconfig, images/kamu-base-with-data-mt/init-workspace.py
- CI: Fixes `kamu-base-with-data-mt` image builds
=> CI: Fixes `kamu-base-with-data-mt` image builds

CHANGELOG.md, src/adapter/http/src/data/ingest_handler.rs, src/adapter/http/src/upload/upload_handler.rs, src/adapter/http/src/upload/upload_service.rs, src/adapter/http/src/upload/upload_service_local.rs, src/adapter/http/src/upload/upload_service_s3.rs, src/adapter/http/tests/harness/test_api_server.rs, src/adapter/http/tests/tests/test_upload_local.rs, src/adapter/http/tests/tests/test_upload_s3.rs, src/app/cli/src/explore/api_server.rs, src/app/cli/src/explore/web_ui_server.rs
Closes  #913
Added `GET /platform/file/upload/{upload_token}` endpoint.
=> Added endpoint to read a recently uploaded file 

.config/nextest.toml, CHANGELOG.md, Cargo.lock, Cargo.toml
Using the patched version of `sqlx`:
- The bulk of the changes from https://github.com/launchbadge/sqlx/pull/3334
- And a little tweak on our part https://github.com/bonega/sqlx/pull/1
=> sqlx + nextest: stabilization

CHANGELOG.md, resources/schema.gql, src/adapter/graphql/src/scalars/data_batch.rs, src/adapter/graphql/src/scalars/data_schema.rs, src/infra/core/tests/tests/test_schema_utils.rs, src/utils/data-utils/src/schema/format.rs
Closes: #746
- Removed deprecated `JSON_LD` in favor of `ND_JSON` in `DataBatchFormat`
- In `DataBatchFormat` introduced `JSON_AOS` format to replace the now deprecated `JSON` in effort to harmonize format names with REST API
- Fixed invalid JSON encoding in `PARQUET_JSON` schema format when column names contain special characters
=> Fix escaping in ParquetJson schema formatter, add JSON_AOS format alias

Cargo.lock, deny.toml, src/adapter/flight-sql/src/service.rs, src/adapter/http/tests/tests/test_data_query.rs, src/domain/opendatafabric/src/dtos/dtos_extra.rs, src/e2e/app/cli/repo-tests/src/commands/test_log_command.rs, src/e2e/app/cli/repo-tests/src/commands/test_search_command.rs, src/infra/core/Cargo.toml
Note: new dependencies change the physical encoding of Parquet files, so there are slight differences in size of the output files. I have confirmed that all block hash differences stem from `physicalHash` of the data blocks which we consider non-reproducible. All other encodings that matter for determinism stayed unchanged. New parquet lib reads old parquet files without issues.
=> Upgrade to datafusion 42.1 and alloy 0.5

CHANGELOG.md, Cargo.lock, Cargo.toml, LICENSE.txt, resources/openapi-mt.json, resources/openapi.json, src/adapter/http/tests/tests/test_data_query.rs
- E2E: reinforce test coverage
- Covered all flow scenarios
- Covered hot REST API endpoints
- Reconfiguring test groups for a small speedup (10%)
- Directory structure grooming
- `KamuApiServerClientExt`: method grouping
- Dataset definition: added possibility to set defaults in templates:
```yaml
fetch:
kind: Container
image: "ghcr.io/kamu-data/fetch-com.defillama:0.1.5"
args:
- --request-interval
- '${{ env.request_interval || 2 }}'
```
- HTTP API errors will now come in JSON format instead of plain text, for example:
```json
{ "message": "Incompatible client version" }
```
- GQL: The `DataQueryResultSuccess` type is extended to the optional `datasets` field, 
which contains information about the datasets participating in the query. Affected API:
- `GQL DataQueries`: the field will be …
=> Release (minor): 0.207.0

images/kamu-base-git/Dockerfile
Sometimes an old executable from the base image was used. This change performs a correct replacement
=> Images, `kamu-base-git`: fix collision of executable files

Makefile
Being able to use `podman` for e2e test.
=> Use KAMU_CONTAINER_RUNTIME_TYPE env var in Makefile

CHANGELOG.md, resources/schema.gql, src/adapter/graphql/src/mutations/dataset_mut/dataset_mut.rs, src/adapter/graphql/src/queries/datasets/dataset_metadata.rs
- Private Datasets:
- GQL, `DatasetMetadata.currentUpstreamDependencies`: indication if datasets not found/not accessed
- GQL, `DatasetMetadata.currentDownstreamDependencies`: exclude datasets that cannot be accessed
=> GQL, DatasetMetadata: be prepared for not accessed datasets

CHANGELOG.md, src/app/cli/src/database.rs, src/app/cli/src/services/config/models.rs, src/utils/database-common/src/db_connection_settings.rs, src/utils/database-common/src/plugins/mysql_plugin.rs, src/utils/database-common/src/plugins/postgres_plugin.rs, src/utils/database-common/src/plugins/sqlite_plugin.rs
=> Extend database pool options

CHANGELOG.md, src/domain/flow-system/services/src/dependencies.rs, src/domain/flow-system/services/src/flow/flow_agent_impl.rs, src/domain/flow-system/services/src/flow/flow_query_service_impl.rs, src/domain/flow-system/services/src/flow/flow_state_helper.rs, src/domain/flow-system/services/src/flow/mod.rs, src/domain/task-system/services/src/task_agent_impl.rs, src/domain/task-system/services/tests/tests/test_task_aggregate.rs, src/infra/flow-system/postgres/.sqlx/query-ffff8fcd2b8ba38101e39fae7f226d466f20c5178f979303dd9974d008524e83.json, src/infra/flow-system/postgres/src/postgres_flow_event_store.rs, src/infra/task-system/postgres/.sqlx/query-4ab9fb67546df9ac01da967d2ac00ddbbbcf898c7646c89aebc06cf83045686e.json, src/infra/task-system/postgres/src/postgres_task_event_store.rs, src/utils/event-sourcing-macros/src/lib.rs, src/utils/event-sourcing/src/aggregate.rs, src/utils/event-sourcing/src/event_store.rs, src/utils/event-sourcing/src/projection.rs
=> Implement batch loading of event sourcing aggregates (Flows, Tasks)

CHANGELOG.md, Cargo.lock, src/domain/datasets/services/Cargo.toml, src/domain/datasets/services/src/dataset_entry_service_impl.rs, src/domain/datasets/services/tests/tests/test_dataset_entry_service.rs
Fix application crash when trying to get dataset for non existing account
=> Fix crash on resolve dataset by invalid account

CHANGELOG.md, src/app/cli/src/commands/inspect_lineage_command.rs, src/domain/core/src/services/provenance_service.rs, src/infra/core/src/services/provenance_service_impl.rs
Closes: https://github.com/kamu-data/kamu-cli/issues/1072
=> Handle panic errors in kamu inspect command

CHANGELOG.md, src/domain/core/src/services/ingest/reader.rs, src/infra/ingest-datafusion/src/readers/mod.rs, src/odf/data-utils/src/lib.rs, src/odf/data-utils/src/schema/parse.rs, src/odf/data-utils/tests/tests/test_schema.rs
Closes: https://github.com/kamu-data/kamu-cli/issues/1077
The result error looks next:
=> Extend parse error with reserved keywords

images/demo/Makefile, images/demo/docker-compose.yml
The images have already been built:
- https://github.com/kamu-data/kamu-cli/pkgs/container/kamu-cli-demo-minio/358089185?tag=0.17.2
- https://github.com/kamu-data/kamu-cli/pkgs/container/kamu-cli-demo-jupyter/358098699?tag=0.17.2
=> images/demo: bump version

CHANGELOG.md, Cargo.lock, Cargo.toml, LICENSE.txt, resources/openapi-mt.json, resources/openapi.json, src/e2e/app/cli/inmem/Cargo.toml, src/e2e/app/cli/mysql/Cargo.toml, src/e2e/app/cli/postgres/Cargo.toml, src/e2e/app/cli/repo-tests/Cargo.toml, src/e2e/app/cli/sqlite/Cargo.toml
- E2E: `repo-tests` crate again contains the `kamu-cli` dependency, but as an optional one
- This way we can correctly reuse the tests in the `kamu-node` repository without affecting the build time
- It also fixes `make sqlx-prepate` developer command
=> Release (patch): `0.225.3`: fix `make sqlx-prepate`

CHANGELOG.md, src/utils/database-common/src/db_error.rs, src/utils/database-common/src/plugins/sqlite_plugin.rs
Closes: #1111
- SQLite: protection against database locking, in case of parallel execution of `kamu` commands.
- Based on `journal_mode=WAL`
The error, was reproduced with the following commands:
```shell
cd images/demo/user-home/01\ -\ Kamu\ Basics\ \(COVID-19\ example\)
rm -rf .kamu && kamu init && kamu sql
kamu repo add kamu-node "odf+https://node.demo.kamu.dev/" && kamu pull kamu-node/kamu/covid19.ontario.case-details
```
=> SQLite: protection against database locking, in case of parallel execution of `kamu` commands. 

CHANGELOG.md, Cargo.lock, Cargo.toml, src/adapter/graphql/Cargo.toml, src/app/cli/Cargo.toml, src/app/cli/src/explore/api_server.rs, src/app/cli/src/explore/web_ui_server.rs, src/utils/server-console/Cargo.toml, src/utils/server-console/assets/index.template.html, src/utils/server-console/src/lib.rs
Addresses: #1141 
This PR
- Adds `graphiql`-based playground which is a better maintained project
- In comparison to old `graphql-playground` the only missing feature I see is the visualisation of Apollo traces. I found them quite useful, so not to lose them I preserved the old version too
- To reduce the duplication I extracted a new crate `server-console` which could become our modular foundation for building web UIs for individual service instances, currently it looks like this:
- In future I expect us to evolve it to allow neat things like:
- Viewing the current configuration
- Modifying logging an metrics configuration in real time for debugging
- Viewing recent request traces etc.
https://github.com/kamu-data/kamu-node/pull/206
=> GraphiQL playground

resources/schema.gql, src/adapter/auth-oso-rebac/tests/tests/test_oso_dataset_authorizer.rs, src/adapter/graphql/src/extensions.rs, src/adapter/graphql/src/queries/data.rs, src/adapter/graphql/src/queries/datasets/dataset_data.rs, src/adapter/graphql/src/scalars/data_query.rs, src/adapter/graphql/src/utils.rs, src/adapter/http/src/smart_protocol/ws_tungstenite_client.rs, src/adapter/http/tests/tests/test_account_info.rs, src/adapter/http/tests/tests/tests_push/test_smart_push_special.rs, src/app/cli/src/commands/pull_command.rs, src/domain/core/src/auth/dataset_action_authorizer.rs, src/domain/core/src/services/query_service.rs, src/odf/metadata/src/errors/access_error.rs, src/odf/storage-http/src/repos/object_repository_http.rs, src/odf/storage-s3/tests/repos/test_object_repository_s3.rs, src/utils/http-common/src/api_error.rs
Closes: kamu-data/kamu-node#214
1) The core of the problem was the introduction of multiple nested error types in `DataFusionError` like:
- `DataFusionError::Shared(Arc<DataFusionError>)` - requires recursively classifying the inner error
- `DataFusionError::Diagnostics(Diag, Box<DataFusionError>)`  - also recursive
- `DataFusionError::Collection(Vec<DataFusionError>)` - need to classify at least by first error
This makes handing these error a nightmare, and some were incorrectly classified as `InternalError` instead of `BadQuery`. This PR improves the classification.
2) Additionally, our `DataQueryResult` was wrapping internal and access errors, preventing internal errors from reaching the top-level handler and not being logged. This PR removes these wrappers and surfaces internal and …
=> Datafusion error classification

CHANGELOG.md, resources/schema.gql, src/adapter/graphql/src/mutations/datasets_mut.rs, src/adapter/graphql/tests/tests/test_gql_datasets.rs, src/app/cli/src/services/config/models.rs, src/e2e/app/cli/repo-tests/src/rest_api/test_gql_query.rs, src/infra/core/Cargo.toml
Closes: #780 
- :warning: Not added but updated & deleted
=> Private Datasets: GQL: make new parameters mandatory, after frontend update

Cargo.lock
RUSTSEC-2025-0024: crossbeam-channel: double free on Drop
https://rustsec.org/advisories/RUSTSEC-2025-0024
=> Fix RUSTSEC-2025-0024

CHANGELOG.md, src/adapter/graphql/src/queries/accounts/account_flow_runs.rs, src/domain/flow-system/domain/src/repos/flow/flow_event_store.rs, src/domain/flow-system/domain/src/services/flow/flow_query_service.rs, src/domain/flow-system/services/src/flow/flow_query_service_impl.rs, src/domain/flow-system/services/tests/tests/test_flow_agent_impl.rs, src/infra/flow-system/inmem/src/flow/inmem_flow_event_store.rs, src/infra/flow-system/postgres/.sqlx/query-2e52fea61863e00be85877026c130c0045767c5bf30397406f428002fa00cca8.json, src/infra/flow-system/postgres/src/postgres_flow_event_store.rs, src/infra/flow-system/sqlite/src/sqlite_flow_event_store.rs
=> Using batch query to count datasets with flows belonging to an account (more listing speedup)

src/utils/database-common/src/lib.rs
This change will remove the redundant dev dependency in `kamu-api-server`:
- https://github.com/kamu-data/kamu-node/blob/f2b8fd4fb875663794fab2f3990c76755a93269e/src/app/api-server/Cargo.toml#L154-L158
=> `database-common`: re-export `PgPoolOptions`

CHANGELOG.md, Cargo.lock, src/adapter/http/Cargo.toml, src/adapter/oauth/Cargo.toml, src/app/cli/Cargo.toml, src/app/cli/src/main.rs, src/infra/accounts/mysql/Cargo.toml, src/infra/accounts/postgres/Cargo.toml, src/infra/accounts/sqlite/Cargo.toml, src/infra/auth-rebac/postgres/Cargo.toml, src/infra/auth-rebac/sqlite/Cargo.toml, src/infra/core/Cargo.toml, src/infra/datasets/postgres/Cargo.toml, src/infra/datasets/sqlite/Cargo.toml, src/infra/flow-system/postgres/Cargo.toml, src/infra/flow-system/sqlite/Cargo.toml, src/infra/messaging-outbox/postgres/Cargo.toml, src/infra/messaging-outbox/sqlite/Cargo.toml, src/infra/task-system/postgres/Cargo.toml, src/infra/task-system/sqlite/Cargo.toml, src/odf/metadata/Cargo.toml, src/utils/database-common/Cargo.toml, src/utils/repo-tools/Cargo.toml
Closes: #1231
Moves TLS configuration out of libraries and into top-level binaries.
Same change will need to be done in `kamu-node`.
=> Move TLS configuration to top level

src/e2e/app/cli/mysql/tests/tests/test_smart_transfer_protocol.rs, src/e2e/app/cli/postgres/tests/tests/test_smart_transfer_protocol.rs, src/e2e/app/cli/sqlite/tests/tests/test_smart_transfer_protocol.rs
In the scope of https://github.com/kamu-data/kamu-cli/pull/1237 we handled a floating race condition issue during simultaneous dataset creating and push ingest. 
PR with removing `flaky` testgroup from the test where it was reproducible.
=> Remove flaky group from push trigger test

CHANGELOG.md, resources/schema.gql, src/adapter/graphql/src/mutations/webhooks_mut/dataset_webhooks_mut.rs, src/adapter/graphql/src/mutations/webhooks_mut/webhook_subscription_mut.rs, src/adapter/graphql/src/scalars/webhook_scalars.rs, src/adapter/graphql/tests/tests/test_gql_webhook_subscriptions.rs, src/domain/webhooks/domain/src/entities/webhook_subscription/webhook_subscription_label.rs, src/domain/webhooks/services/tests/tests/services/test_webhook_dataset_removal_handler.rs, src/domain/webhooks/services/tests/tests/services/test_webhook_delivery_scheduler.rs, src/domain/webhooks/services/tests/tests/services/test_webhook_delivery_worker_impl.rs, src/domain/webhooks/services/tests/tests/use_cases/test_create_webhook_subscription_use_case.rs, src/domain/webhooks/services/tests/tests/use_cases/test_update_webhook_subscription_use_case.rs, src/domain/webhooks/services/tests/tests/use_cases/webhook_subscription_use_case_harness.rs, src/infra/webhooks/repo-tests/src/helpers.rs, src/infra/webhooks/repo-tests/src/webhook_subscription_event_store_test_suite.rs
Closes: #1259
Added explicit validation for webhook subscription label length constraints.
=> Added missing length validation for webhook subscription labels.

CHANGELOG.md, src/domain/accounts/services/src/use_cases/create_account_use_case_impl.rs, src/domain/accounts/services/tests/tests/use_cases/test_create_account_use_case_impl.rs
- `CreateAccountUseCaseImpl`: added sending `AccountLifecycleMessage`
=> `CreateAccountUseCaseImpl`: added sending `AccountLifecycleMessage`

src/adapter/graphql/Cargo.toml, src/adapter/http/Cargo.toml, src/app/cli/Cargo.toml, src/utils/observability/Cargo.toml, src/utils/observability/src/build_info.rs, src/utils/observability/src/health.rs, src/utils/observability/src/metrics.rs
This allows using `observability` crate in other projects that may not want `dill` as a dependency, or may need to compile in stable rust that `dill` does not yet support.
=> observability: make dill dependency optional

CHANGELOG.md, Cargo.lock, resources/schema.gql, src/adapter/graphql/Cargo.toml, src/adapter/graphql/src/queries/tasks/task_outcome.rs, src/adapter/task-webhook/Cargo.toml, src/adapter/task-webhook/src/runners/deliver_webhook_task_runner.rs, src/adapter/task-webhook/src/task_errors/mod.rs, src/adapter/task-webhook/src/task_errors/task_error_webhook_delivery.rs, src/domain/webhooks/domain/src/services/webhook_delivery_worker.rs, src/domain/webhooks/domain/src/services/webhook_sender.rs, src/domain/webhooks/services/src/services/webhook_delivery_worker_impl.rs, src/domain/webhooks/services/src/services/webhook_sender_impl.rs, src/domain/webhooks/services/tests/tests/services/test_webhook_delivery_worker_impl.rs
Closes: #1335
Extended support for webhook delivery errors, differentiating between:
- connection failure
- response timeout
- bad status code in response
Handling at: domain level, task adapter level, GQL API level.
=> Extended handling of webhook delivery errors

src/app/cli/Cargo.toml, src/domain/core/Cargo.toml, src/odf/odf/Cargo.toml, src/odf/odf/src/lib.rs
It must be possible to use top-level `odf` library without `datafusion` as a dependency.
=> ODF: Hide datafusion under a feature flag

resources/schema.gql, src/adapter/graphql/src/mutations/molecule_mut.rs, src/adapter/graphql/src/queries/molecule.rs, src/adapter/graphql/tests/tests/test_gql_custom_molecule.rs, src/domain/core/src/services/dataset_registry.rs, src/domain/core/src/services/query_service.rs, src/infra/core/src/services/query_service_impl.rs, src/odf/data-utils/src/data/dataframe_ext.rs
Adds `{ molecule { activity } }` GQL endpoint similar to per project `{ molecule { project { activity } } }`.
Currently implemented as brute force `union all + order by + limit` across all announcements dataset, but allows us to add caching and other improvements under the hood in future.
=> Molecule: global announcements feed

CHANGELOG.md, Cargo.lock, src/adapter/graphql/Cargo.toml, src/adapter/graphql/src/config.rs, src/adapter/graphql/src/queries/datasets/dataset_request_state.rs
Closes: #1371
Removes a config option that was added for the brief period of migrating collection and versioned file datasets to ODF schema.
=> Drop archetype inference from schema compatibility option

Cargo.lock, Cargo.toml, src/app/cli/Cargo.toml
Continues:
- https://github.com/kamu-data/kamu-cli/pull/1387
Since the original issue has been fixed:
- https://github.com/aws/aws-lc-rs/issues/889
=> `aws-lc-rs`: unpin version
