kamu-data/kamu-cli

src/main/scala/dev/kamu/cli/CliParser.scala, src/main/scala/dev/kamu/cli/Kamu.scala, src/main/scala/dev/kamu/cli/MetadataRepository.scala, src/main/scala/dev/kamu/cli/commands/PullCommand.scala, src/main/scala/dev/kamu/cli/utility/DependencyGraph.scala, src/test/scala/dev/kamu/cli/DatasetFactory.scala, src/test/scala/dev/kamu/cli/KamuPullDerivativeSpec.scala, src/test/scala/dev/kamu/cli/MetadataRepositorySpec.scala, src/test/scala/dev/kamu/cli/TestUtils.scala, src/test/scala/dev/kamu/cli/utility/DependencyGraphSpec.scala
`kamu pull` is able to resolve dependencies between datasets now.
=> Added dataset dependency resolution

CHANGELOG.md, core.coordinator/src/main/scala/dev/kamu/cli/commands/AssignWatermarkCommand.scala, core.coordinator/src/main/scala/dev/kamu/cli/commands/LogCommand.scala, core.coordinator/src/main/scala/dev/kamu/cli/ingest/IngestService.scala, core.coordinator/src/main/scala/dev/kamu/cli/ingest/fetch/HTTPSource.scala, core.coordinator/src/main/scala/dev/kamu/cli/metadata/MetadataChain.scala, core.coordinator/src/main/scala/dev/kamu/cli/transform/TransformService.scala
Maintaining refs according to the ODF spec.
Also small fix for following redirects.
Fixes: #26
=> Maintain chain block refs

CHANGELOG.md, Cargo.lock, docs/first_steps.md, kamu-cli/Cargo.toml, kamu-cli/src/cli_parser.rs, kamu-cli/src/commands/complete_command.rs, kamu-cli/src/commands/new_dataset_command.rs, kamu-cli/src/main.rs, kamu-core-test/Cargo.toml, kamu-core/Cargo.toml, opendatafabric/Cargo.toml
=> Add detailed command help and examples

.github/workflows/release.yaml, CHANGELOG.md, Cargo.lock, kamu-cli/Cargo.toml, kamu-cli/src/cli_parser.rs, kamu-core-test/Cargo.toml, kamu-core/Cargo.toml, opendatafabric/Cargo.toml
=> Fix command help and change release binary name

CHANGELOG.md, Cargo.lock, docs/examples/currency_conversion.md, docs/examples/trading.md, kamu-cli/Cargo.toml, kamu-cli/src/cli_parser.rs, kamu-cli/src/commands/add_command.rs, kamu-cli/src/commands/common.rs, kamu-cli/src/commands/delete_command.rs, kamu-cli/src/commands/mod.rs, kamu-cli/src/main.rs, kamu-core-test/Cargo.toml, kamu-core/Cargo.toml, opendatafabric/Cargo.toml
=> Add --replace flag

CHANGELOG.md, Cargo.lock, kamu-cli/Cargo.toml, kamu-cli/src/commands/notebook_command.rs, kamu-cli/src/commands/pull_command.rs, kamu-cli/src/commands/sql_server_command.rs, kamu-cli/src/commands/sql_shell_command.rs, kamu-core-test/Cargo.toml, kamu-core/Cargo.toml, kamu-core/src/infra/explore/sql_shell_impl.rs, opendatafabric/Cargo.toml, opendatafabric/src/serde/flatbuffers/odf_generated.rs, opendatafabric/src/serde/flatbuffers/serdes.rs
=> Handle empty workspace in sql command

CHANGELOG.md, Cargo.lock, kamu-cli/Cargo.toml, kamu-cli/src/commands/sql_server_command.rs, kamu-core-test/Cargo.toml, kamu-core/Cargo.toml, kamu-core/src/infra/explore/sql_shell_impl.rs, opendatafabric/Cargo.toml
FYI @coldeasy, hopefully this fixes your issue.
=> Fix sql init file lifetime

.github/workflows/release-images.yaml, examples/reth-vs-snp500/init-s3.sh, images/Makefile, images/kamu-base-with-data/Dockerfile, kamu-cli/src/cli_parser.rs
FYI @zaychenko-sergei 
Will have to merge now as I cannot debug the CI action until it hits `master`
=> CI: Automate building OCI images

CHANGELOG.md, Cargo.lock, LICENSE.txt, images/Makefile, images/demo/Makefile, kamu-adapter-graphql/Cargo.toml, kamu-cli/Cargo.toml, kamu-cli/src/config.rs, kamu-core/Cargo.toml, opendatafabric/Cargo.toml, utils/container-runtime/Cargo.toml
Yaml serialized no longer includes `---\n` prefix which I was foolishly stripping without asserting on line content.
=> Fix config command ouptut truncation

CHANGELOG.md, Cargo.lock, LICENSE.txt, images/Makefile, images/demo/Makefile, kamu-adapter-graphql/Cargo.toml, kamu-adapter-graphql/src/scalars/odf_generated.rs, kamu-cli/Cargo.toml, kamu-cli/src/commands/pull_command.rs, kamu-cli/tests/tests/test_pull_command.rs, kamu-core/Cargo.toml, kamu-core/src/infra/engine/engine_spark.rs, kamu-core/src/infra/ingest/fetch_service.rs, kamu-core/src/testing/metadata_factory.rs, kamu-core/tests/tests/ingest/test_fetch.rs, opendatafabric/Cargo.toml, opendatafabric/schemas/odf.fbs, opendatafabric/src/dtos/dtos_dyntraits_generated.rs, opendatafabric/src/dtos/dtos_generated.rs, opendatafabric/src/serde/flatbuffers/convertors_generated.rs, opendatafabric/src/serde/flatbuffers/proxies_generated.rs, opendatafabric/src/serde/yaml/derivations_generated.rs, opendatafabric/tests/tests/test_serde_yaml.rs, resources/schema.gql, tools/src/create_test_workspace.rs, utils/container-runtime/Cargo.toml
Adds support for things like:
```
fetch:
kind: url
url: https://example.com
headers:
- name: Authorization
value: EXAMPLE_TOKEN
```
=> Support extra headers in FetchStep schema

Cargo.lock, kamu-cli/src/cli_commands.rs, kamu-cli/src/cli_parser.rs
=> Cleanup of optional vs required command line switches

CHANGELOG.md, images/demo/Dockerfile.jupyter, images/demo/kamu/requirements.txt, images/jupyter/Dockerfile, images/jupyter/requirements.txt
=> Upgrade and unhack sparkmagic

.github/workflows/build.yaml, .github/workflows/release-images.yaml, .github/workflows/release.yaml, CHANGELOG.md, Cargo.lock, LICENSE.txt, images/Makefile, images/demo/Makefile, kamu-adapter-graphql/Cargo.toml, kamu-cli/Cargo.toml, kamu-core/Cargo.toml, kamu-core/tests/utils/http_file_server.rs, opendatafabric/Cargo.toml, utils/container-runtime/Cargo.toml
- Using latest `arrow` and `datafusion`
- Also updated many other dependencies that dependabot complains about
=> Upgrade arrow and other deps

kamu-core/src/infra/engine/engine_odf.rs
This small change creates clear spans to separate engine initialization/startup and execution of the operation, so we could easily tell how much time each takes.
Also making sure that while we wait for engine to spawn we don't block event loop. We really should convert `ContainerRuntime` to async ASAP to get rid of all `tokio::spawn_blocking()`.
=> Improve ODF engine tracing & timings

images/demo/Dockerfile.jupyter, images/jupyter/Dockerfile
=> Fix Jupyter image build

CHANGELOG.md, Cargo.lock, Cargo.toml, LICENSE.txt, src/infra/core/src/ingest/ingest_task.rs
=> Fix spark ingest with relative path

CHANGELOG.md, Cargo.lock, Cargo.toml, LICENSE.txt
- As an agent of goodness, I'd like to fix our CI builds ([failed lint step](https://github.com/kamu-data/kamu-cli/actions/runs/7251901915/job/19755235139?pr=373#step:5:12240) example)
=> 0.147.2 (minor update): address RUSTSEC-2023-0074

CHANGELOG.md, resources/schema.gql, src/adapter/graphql/src/queries/datasets/dataset_metadata.rs, src/adapter/graphql/tests/tests/mod.rs, src/adapter/graphql/tests/tests/test_gql_metadata.rs, src/domain/core/src/services/ingest/polling_ingest_service.rs, src/domain/core/src/services/ingest/push_ingest_service.rs, src/domain/core/src/services/transform_service.rs, src/infra/core/src/ingest/polling_ingest_service_impl.rs, src/infra/core/src/ingest/push_ingest_service_impl.rs, src/infra/core/src/testing/metadata_factory.rs, src/infra/core/src/transform_service_impl.rs, src/infra/core/tests/tests/test_pull_service_impl.rs
=> Add currentPushSources GQL endpoint

CHANGELOG.md, src/adapter/http/tests/harness/common_harness.rs, src/app/cli/src/explore/notebook_server_impl.rs, src/infra/core/src/ingest/fetch_service.rs, src/infra/core/src/utils/cached_object.rs
=> tokio::fs::file's: fix missed flush()'es

CHANGELOG.md, src/infra/core/src/ingest/polling_ingest_service_impl.rs, src/infra/ingest-datafusion/src/writer.rs
=> PollingIngestServiceImpl::ingest_loop(): fix iterative processing

CHANGELOG.md, src/app/cli/src/cli_commands.rs, src/app/cli/src/cli_parser.rs, src/app/cli/src/commands/system_api_server_run_command.rs, src/app/cli/src/explore/api_server.rs
Related issue https://github.com/kamu-data/kamu-cli/issues/376
=> Add get-token flag to api-server start

.github/ISSUE_TEMPLATE/bug_report.yaml
Fixes left comments from https://github.com/kamu-data/kamu-cli/pull/409
=> GitHub templates follow-up fixes

CHANGELOG.md, src/domain/core/src/services/dependency_graph_repository.rs, src/infra/core/src/dependency_graph_repository_inmem.rs, src/infra/core/src/dependency_graph_service_inmem.rs, src/infra/core/tests/tests/test_dependency_graph_inmem.rs
Closes: https://github.com/kamu-data/kamu-cli/issues/420
=> DependencyGraphServiceInMemory: init existing datasets (w/o dependencies)

DEVELOPER.md
Closes: https://github.com/kamu-data/kamu-cli/issues/423
=> DEVELOPER.md: add a note about sccache

CHANGELOG.md, src/adapter/auth-oso/src/schema.polar
Closes: https://github.com/kamu-data/kamu-cli/issues/433
=> Fix sporadic `OsoDatasetAuthorizer::get_allowed_actions()` error

CHANGELOG.md, src/app/cli/src/cli_parser.rs
Closes: https://github.com/kamu-data/kamu-cli/issues/443
=> kamu add: correct a link in help examples

src/app/cli/src/commands/complete_command.rs, src/domain/core/src/entities/metadata_stream.rs, src/infra/core/tests/tests/repos/test_dataset_repository_shared.rs
Address @zaychenko-sergei 's comments left in https://github.com/kamu-data/kamu-cli/pull/446
Related issue: https://github.com/kamu-data/kamu-cli/issues/332
=> clippy: manual fixes follow-up fixes

CHANGELOG.md, src/app/cli/src/cli_commands.rs, src/app/cli/src/cli_parser.rs, src/app/cli/src/commands/login_command.rs, src/app/cli/src/commands/logout_command.rs, src/app/cli/src/services/odf_server/access_token_registry_service.rs
=> 448 loginlogout commands crash

CHANGELOG.md, src/adapter/graphql/src/scalars/flow_configuration.rs, src/adapter/graphql/tests/tests/test_gql_dataset_flow_configs.rs
Closes: #458
Improved TimeDelta validation & internal conversions.
Added solid test coverage.
=> Flow configuration: improved TimeDelta validation & internal conversions

CHANGELOG.md, src/domain/core/src/entities/engine.rs, src/domain/core/src/services/ingest/polling_ingest_service.rs, src/infra/core/src/ingest/polling_ingest_service_impl.rs, src/infra/core/src/ingest/prep_service.rs, src/infra/core/tests/tests/ingest/test_prep.rs
Closes: https://github.com/kamu-data/kamu-cli/issues/340
=> Write pipe stderr to file

Cargo.lock, src/app/cli/Cargo.toml, src/app/cli/tests/tests/mod.rs, src/app/cli/tests/tests/test_datafusion_cli.rs
Closes: https://github.com/kamu-data/kamu-cli/issues/228
=> Add integration test for DataFusion SQL console

Cargo.lock
Fix pipeline `cargo deny check` step
=> Update iana-time-zone crate version

Cargo.toml
=> clippy: simplify config

CHANGELOG.md, src/app/cli/src/cli_commands.rs, src/app/cli/src/commands/notebook_command.rs, src/app/cli/src/commands/sql_server_command.rs, src/app/cli/src/commands/sql_server_livy_command.rs, src/app/cli/src/commands/system_diagnose_command.rs, src/app/cli/src/error.rs, src/app/cli/src/error_fmt.rs, src/app/cli/src/explore/livy_server_impl.rs, src/app/cli/src/explore/notebook_server_impl.rs, src/app/cli/src/explore/sql_shell_impl.rs
Closes: https://github.com/kamu-data/kamu-cli/issues/483
=> Implement printilg err files with errors

CHANGELOG.md, src/adapter/http/src/smart_protocol/axum_server_pull_protocol.rs, src/adapter/http/src/smart_protocol/axum_server_push_protocol.rs, src/adapter/http/src/smart_protocol/messages.rs, src/adapter/http/src/smart_protocol/protocol_dataset_helper.rs, src/adapter/http/src/smart_protocol/ws_tungstenite_client.rs
Should eliminate issues in metadata block caching implementation.
=> Hotfix: modeling mistake in Smart Transfer Protocol 

CHANGELOG.md, src/app/cli/src/cli_commands.rs, src/app/cli/src/commands/delete_command.rs, src/app/cli/src/commands/verify_command.rs, src/domain/core/src/services/dependency_graph_service.rs, src/domain/core/src/services/verification_service.rs, src/infra/core/src/dependency_graph_service_inmem.rs, src/infra/core/tests/tests/test_dependency_graph_inmem.rs
Closes: https://github.com/kamu-data/kamu-cli/issues/429
=> Add recursive flag for verify and delete commands

src/infra/core/src/pull_service_impl.rs
=> Ignore trailing slash when infering dataset name

CHANGELOG.md, src/app/cli/src/cli_commands.rs, src/app/cli/src/cli_parser.rs, src/app/cli/src/commands/init_command.rs
=> Add exists-ok flag to init command

CHANGELOG.md, Cargo.lock, Cargo.toml, LICENSE.txt, resources/schema.gql, src/adapter/graphql/src/mutations/flows_mut/dataset_flow_errors.rs, src/adapter/graphql/src/mutations/flows_mut/dataset_flow_runs_mut.rs, src/adapter/graphql/tests/tests/test_gql_dataset_flow_runs.rs, src/domain/flow-system/src/services/flow/flow_service.rs, src/domain/flow-system/src/services/flow_configuration/flow_configuration_service.rs, src/infra/flow-system-inmem/src/services/flow/flow_service_inmem.rs, src/infra/flow-system-inmem/src/services/flow_configuration/flow_configuration_service_inmem.rs
=> 517 flows simplify cancellation api

CHANGELOG.md, images/Makefile, images/demo/Dockerfile.jupyter, images/demo/Makefile, images/demo/docker-compose.yml, images/jupyter/Dockerfile, images/kamu-base-with-data-mt/.kamuconfig, images/kamu-base-with-data-mt/Dockerfile, src/infra/core/src/utils/docker_images.rs
Closes: #533 
- Using a workaround to install working `mapboxgl` library in Jupyter
- Added a `.kamuconfig` to `with-data-mt` image to allow running `ui` and `api-server` from it without encountering unresolved accounts issue
=> Fix mapboxgl in jupyter image

CHANGELOG.md, src/infra/core/tests/tests/ingest/test_writer.rs, src/infra/ingest-datafusion/src/visitor.rs, src/infra/ingest-datafusion/src/writer.rs
=> DataWriterDataFusionBuilder::with_metadata_state_scanned(): respect the initial visitior decition

CHANGELOG.md, examples/flight-sql/python/client_flightsql_adbc.py, examples/flight-sql/python/client_flightsql_dbapi2.py, examples/flight-sql/python/client_flightsql_sqlalchemy.py, examples/flight-sql/python/client_jdbc.py, src/adapter/flight-sql/src/service.rs
-  Improved Python connectivity examples (ADBC, Sqlalchemy, DBAPI2, JDBC)
- Fix invalid `location` info returned by FlightSQL protocol in `FlightInfo` that might've been causing errors in some client libraries and slowing down others.
=> Fix location in FlightInfo

resources/cli-reference.md, src/app/cli/src/cli_commands.rs, src/app/cli/src/cli_parser.rs, src/app/cli/src/commands/system_generate_token_command.rs, src/app/cli/src/services/accounts/account_service.rs, src/infra/core/src/auth/authentication_service_impl.rs
- Allows to generate token for `password` (dummy) auth provider
- Allows to set token expiration time
=> Improve generate-token command

CHANGELOG.md, src/adapter/graphql/src/queries/datasets/dataset_endpoints.rs
Tracking issue: https://github.com/kamu-data/kamu-cli/issues/579
=> GraphQL Dataset Endpoints: tenant insensitive paths

CHANGELOG.md, Cargo.lock, Cargo.toml, LICENSE.txt, src/adapter/http/Cargo.toml, src/adapter/http/src/smart_protocol/ws_tungstenite_client.rs
Related issue: https://github.com/kamu-data/kamu-cli/issues/562
=> Set correct ODF push/pull websocket protocol

CHANGELOG.md, resources/schema.gql, src/adapter/graphql/src/queries/flows/flow.rs, src/adapter/graphql/tests/tests/test_gql_dataset_flow_runs.rs
Extend graphQL compacting empty result
=> Extend compacting empty result

CHANGELOG.md, Cargo.lock, Cargo.toml, LICENSE.txt, src/adapter/graphql/src/queries/datasets/dataset_endpoints.rs
Related issue: https://github.com/kamu-data/kamu-cli/issues/577
=> DatasetEndpoints::rest(): fix query URL + Release (minor): 0.175.0

CHANGELOG.md, Cargo.lock, Cargo.toml, LICENSE.txt
Release 0.176.1 with minor fixes related to results for `setFlowConfig` mutations
=> Release 0.176.1

resources/schema.gql, src/adapter/graphql/src/scalars/engine_desc.rs, src/domain/core/src/services/query_service.rs, src/infra/core/src/query_service_impl.rs
Closes: #456 
PR in Web UI: https://github.com/kamu-data/kamu-web-ui/pull/305
=> Risingwave in UI

Cargo.lock, Cargo.toml, deny.toml, src/adapter/flight-sql/Cargo.toml, src/adapter/flight-sql/src/service.rs, src/adapter/graphql/Cargo.toml, src/adapter/http/Cargo.toml, src/adapter/odata/Cargo.toml, src/app/cli/Cargo.toml, src/domain/core/Cargo.toml, src/domain/flow-system/domain/Cargo.toml, src/domain/opendatafabric/Cargo.toml, src/infra/core/Cargo.toml, src/infra/core/src/engine/engine_odf.rs, src/infra/core/src/query/mod.rs, src/infra/ingest-datafusion/Cargo.toml, src/infra/ingest-datafusion/src/merge_strategies/snapshot.rs, src/infra/ingest-datafusion/src/writer.rs, src/utils/data-utils/Cargo.toml, src/utils/data-utils/src/data/dataframe_ext.rs, src/utils/datafusion-cli/Cargo.toml, src/utils/datafusion-cli/src/catalog.rs, src/utils/datafusion-cli/src/command.rs, src/utils/datafusion-cli/src/exec.rs, src/utils/datafusion-cli/src/functions.rs, src/utils/datafusion-cli/src/helper.rs, src/utils/datafusion-cli/src/lib.rs, src/utils/datafusion-cli/src/object_storage.rs, src/utils/datafusion-cli/src/print_options.rs
This test upgrade revealed an issue with future sizes and stack overflows:
https://github.com/apache/arrow-datafusion/issues/9893
=> Upgrade datafusion 37

.github/workflows/build.yaml, .github/workflows/release.yaml
Related issue: https://github.com/kamu-data/kamu-node/issues/70
=> GHA improvements + Updated yanked crate (rustix)

CHANGELOG.md, Cargo.lock, Cargo.toml, LICENSE.txt, src/domain/accounts/domain/src/entities/current_account_subject.rs, src/domain/accounts/domain/src/entities/predefined_accounts_config.rs
Related issue: https://github.com/kamu-data/kamu-node/issues/45
=> Adding derived traits needed for `kamu-node`

CHANGELOG.md, resources/cli-reference.md, src/app/cli/src/cli_commands.rs, src/app/cli/src/cli_parser.rs, src/app/cli/src/commands/delete_command.rs
=> Add `--all` flag to delete command

CHANGELOG.md, Cargo.lock, Cargo.toml, LICENSE.txt
=> Release 0.183.0

images/demo/Makefile
Closes: no issue, just a minor thing
=> Jupyter demo: add "make prepare-multi-arch-build"

images/demo/Makefile
Related issue:
- https://github.com/kamu-data/kamu-cli/issues/678
---
The image has already been built
- https://github.com/kamu-data/kamu-cli/pkgs/container/kamu-cli-demo-jupyter/232928356?tag=0.14.1
=> kamu-cli-demo-jupyter: release (patch) 0.14.1

CHANGELOG.md, Cargo.lock, Cargo.toml, LICENSE.txt
=> Bump version to 0.188.4

CHANGELOG.md, Cargo.lock, Cargo.toml, LICENSE.txt, resources/schema.gql, src/adapter/graphql/src/mutations/auth_mut.rs, src/adapter/graphql/tests/tests/test_auth.rs
Add missed field to create access token gql API
=> Add missed field to create at gql API

CHANGELOG.md, Cargo.lock, Cargo.toml, LICENSE.txt, src/utils/data-utils/src/schema/parse.rs
=> Release  v0.190.0

.github/workflows/release-images.yaml, images/Makefile
=> Add new image to workflow

Makefile
Fix the new crate name in makefile
=> Fix new crate name in make file

CHANGELOG.md, Cargo.lock, Cargo.toml, LICENSE.txt, src/infra/datasets/inmem/src/repos/dataset_env_var_repository_inmem.rs, src/infra/datasets/repo-tests/src/dataset_env_var_repository_test_suite.rs
Fix DatasetEnvVar inmem deleting
=> Fix datasetEnvVar inmem deleting

src/adapter/http/src/smart_protocol/axum_server_protocol_common.rs, src/adapter/http/src/smart_protocol/axum_server_push_protocol.rs, src/adapter/http/src/smart_protocol/ws_tungstenite_client.rs
=> Add server websocket closing messages

src/app/cli/src/commands/ui_command.rs
=> Fix web ui build

images/sqlx-cli-with-migrations/scripts/fetch-db-secret.sh, src/domain/datasets/domain/src/entities/dataset_env_var.rs
Fix special characterss in database string in migration script
=> Fix special chars in db string

CHANGELOG.md, Cargo.lock, Cargo.toml, LICENSE.txt, src/adapter/odata/Cargo.toml
=> Release 0.191.3

CHANGELOG.md, Cargo.lock, Cargo.toml, LICENSE.txt, src/app/cli/src/database.rs, src/app/cli/src/services/config/models.rs, src/utils/database-common/src/db_connection_settings.rs, src/utils/database-common/src/db_provider.rs, src/utils/database-common/src/password/provider/db_aws_secret_password_provider.rs, src/utils/database-common/src/plugins/mysql_plugin.rs, src/utils/database-common/src/plugins/postgres_plugin.rs, src/utils/database-common/src/plugins/sqlite_plugin.rs
Fix db password parsing in a crate
=> Fix db password parsing in crate

DEVELOPER.md, images/demo/Makefile, images/demo/docker-compose.yml
=> Update jupyter version and doc

CHANGELOG.md, Cargo.lock, Cargo.toml, LICENSE.txt
=> Release 0.191.5

CHANGELOG.md, src/adapter/graphql/tests/tests/test_gql_dataset_flow_runs.rs, src/domain/flow-system/domain/src/entities/flow/flow_outcome.rs, src/domain/flow-system/services/src/flow/flow_service_impl.rs, src/domain/task-system/domain/src/entities/task_status.rs, src/domain/task-system/services/src/task_executor_impl.rs
Closes: https://github.com/kamu-data/kamu-cli/issues/743
=> Return RootDatasetCompacted err for manual triggered flows

CHANGELOG.md, Cargo.lock, DEVELOPER.md, src/utils/container-runtime/Cargo.toml, src/utils/container-runtime/src/runtime.rs
Closes: https://github.com/kamu-data/kamu-cli/issues/68
- Fixed container runtime for systems using SELinux
=> container-runtime: respect for Linux systems with SELinux

CHANGELOG.md, Cargo.lock, Cargo.toml, LICENSE.txt
=> Release 0.192.0

CHANGELOG.md, src/adapter/http/tests/harness/client_side_harness.rs, src/app/cli/src/app.rs, src/domain/datasets/services/src/dataset_env_var_service_null.rs, src/domain/datasets/services/src/dataset_env_var_service_static_impl.rs, src/domain/datasets/services/src/dataset_key_value_service_sys_env.rs, src/domain/datasets/services/src/lib.rs, src/infra/core/tests/tests/engine/test_engine_io.rs, src/infra/core/tests/tests/engine/test_engine_transform.rs, src/infra/core/tests/tests/ingest/test_fetch.rs, src/infra/core/tests/tests/ingest/test_polling_ingest.rs
Fix panic for execute transform flow
=> Fix panic for execute transform flow

CHANGELOG.md, Cargo.lock, Cargo.toml, LICENSE.txt
=> Release 0.194.0

CHANGELOG.md, resources/schema.gql, src/adapter/graphql/src/mutations/flows_mut/flows_mut_utils.rs, src/adapter/graphql/src/scalars/flow_configuration.rs, src/adapter/graphql/tests/tests/test_gql_dataset_flow_runs.rs, src/app/cli/src/app.rs, src/domain/flow-system/domain/src/entities/shared/flow_type.rs, src/domain/flow-system/domain/src/entities/shared/reset_rule.rs, src/domain/flow-system/services/src/flow/flow_service_impl.rs, src/domain/flow-system/services/tests/tests/test_flow_service_impl.rs, src/domain/task-system/domain/src/entities/logical_plan.rs, src/domain/task-system/services/src/task_executor_impl.rs
Add `recursive` flag to GQL api reset flow
=> Add RecursiveCompaction flag to GQL api reset flow

CHANGELOG.md, Cargo.lock, Cargo.toml, LICENSE.txt
=> Relesae 0.194.1

CHANGELOG.md, Cargo.lock, Cargo.toml, LICENSE.txt, migrations/postgres/20240816113232_add_reset_type.sql, migrations/sqlite/20240422100311_flow_configuration_events.sql
Add reset variant to database migration
=> Add reset variant to database migration

CHANGELOG.md, migrations/postgres/20240819135229_modify_access_token_uniq.sql, migrations/sqlite/20240819135229_modify_access_token_uniq.sql, src/domain/accounts/services/src/authentication_service_impl.rs, src/infra/accounts/inmem/src/repos/inmem_access_token_repository.rs, src/infra/accounts/inmem/tests/repos/test_inmem_access_token_repository.rs, src/infra/accounts/postgres/tests/repos/test_postgres_access_token_repository.rs, src/infra/accounts/repo-tests/src/access_token_repository_test_suite.rs, src/infra/accounts/sqlite/tests/repos/test_sqlite_access_token_repository.rs
Closes: https://github.com/kamu-data/kamu-cli/issues/776
https://github.com/kamu-data/kamu-node/issues/115
=> Access token improvements

CHANGELOG.md, Cargo.lock, Cargo.toml, LICENSE.txt
=> Release 0.197.0

CHANGELOG.md, src/infra/core/src/ingest/fetch_service/container.rs, src/infra/core/tests/tests/ingest/test_fetch.rs
=> Container cmd interpolation

CHANGELOG.md, Cargo.lock, Cargo.toml, LICENSE.txt
=> Release v.0.199.3

examples/covid/Covid Using Graphs in Jupyter Notebook.ipynb, examples/covid/alberta.case-details.hm.yaml, examples/covid/british-columbia.case-details.hm.yaml, examples/covid/canada.case-details.yaml, examples/covid/ontario.case-details.hm.yaml, examples/covid/quebec.case-details.hm.yaml, examples/housing_prices/ca.vancouver.opendata.property.tax-reports.yaml, examples/housing_prices/heatmap.ipynb
Closes: #803 
Related issue: ccodwg/Covid19Canada#44
For review of Nilay. I created a Covid Jupyter Notebook with a new yaml. I also believe I ahve fixed two errors found in Housing prices, One from the taxes yaml and the other from the heatmap jupyter notebook
=> Fixes errors in Housing prices for tax yaml and creating a Covid notebook 

.github/workflows/build.yaml, CHANGELOG.md, Cargo.lock, Cargo.toml, LICENSE.txt, src/app/cli/src/explore/web_ui_server.rs
- Fixed build regression, in case `web-ui` feature flag is used
=> Hotfix: `web-ui` feature building + CI: testing `web-ui` feature building

.github/workflows/build.yaml
=> CI: use comma-separated feature list

CHANGELOG.md, src/adapter/http/src/smart_protocol/axum_server_push_protocol.rs, src/adapter/http/src/smart_protocol/errors.rs, src/adapter/http/src/smart_protocol/messages.rs, src/adapter/http/src/smart_protocol/ws_tungstenite_client.rs, src/infra/core/src/repos/dataset_repository_local_fs.rs, src/infra/core/src/utils/ipfs_wrapper.rs, src/infra/core/tests/tests/repos/test_dataset_repository_local_fs.rs, src/infra/core/tests/tests/repos/test_dataset_repository_shared.rs, src/infra/core/tests/tests/test_sync_service_impl.rs
Closes: https://github.com/kamu-data/kamu-cli/issues/846
=> Fix duplicate dataset creation in fs mode

CHANGELOG.md, src/adapter/flight-sql/Cargo.toml, src/adapter/graphql/Cargo.toml, src/adapter/http/Cargo.toml, src/adapter/odata/Cargo.toml, src/app/cli/Cargo.toml, src/domain/datasets/domain/Cargo.toml, src/domain/datasets/services/src/dataset_entry_indexer.rs, src/domain/flow-system/services/Cargo.toml, src/e2e/app/cli/common/Cargo.toml, src/e2e/app/cli/repo-tests/Cargo.toml, src/infra/core/Cargo.toml, src/infra/ingest-datafusion/Cargo.toml, src/utils/data-utils/Cargo.toml, src/utils/database-common-macros/Cargo.toml, src/utils/database-common-macros/src/lib.rs, src/utils/event-sourcing-macros/Cargo.toml, src/utils/time-source/Cargo.toml
Closes: #871
Fixing https://github.com/kamu-data/kamu-cli/pull/872#discussion_r1785905204 (follow-up PR)
- `DatasetEntryIndexer`: memorization (account name/id mapping )
- Updated our crate dependencies so they can be built in isolation
=> `DatasetEntryIndexer`: memorization + Updated our crate dependencies so they can be built in isolation

examples/query-commitments/README.md, examples/query-commitments/example.py, examples/query-commitments/requirements.in, examples/reth-vs-snp500/init-odf-all.sh, examples/reth-vs-snp500/init-odf.sh
Adds query commitment validation example along with validation failure examples.
Adds a few convenience scripts for pulling data.
=> Add query commitments example

CHANGELOG.md, Cargo.lock, Cargo.toml, LICENSE.txt
=> Release 0.205.0

src/e2e/app/cli/inmem/tests/tests/test_smart_transfer_protocol.rs, src/e2e/app/cli/postgres/tests/tests/test_smart_transfer_protocol.rs, src/e2e/app/cli/repo-tests/src/test_smart_transfer_protocol.rs, src/e2e/app/cli/sqlite/tests/tests/test_smart_transfer_protocol.rs
=> Add push test from registered repo

CHANGELOG.md, src/adapter/http/src/smart_protocol/ws_tungstenite_client.rs
Closes: https://github.com/kamu-data/kamu-cli/issues/908
Error after fix:
=> Fix push flow command error

CHANGELOG.md, migrations/postgres/20241024110339_dataset_entries_reindexing.sql, migrations/sqlite/20241024110339_dataset_entries_reindexing.sql, src/domain/datasets/services/src/dataset_entry_indexer.rs, src/utils/database-common-macros/src/lib.rs
- `DatasetEntryIndexer`: guarantee startup after `OutboxExecutor` for a more predictable initialization
- Add `DatasetEntry`'is re-indexing migration
=> DB: add `DatasetEntry`'is re-indexing migration

CHANGELOG.md, Cargo.lock, Cargo.toml, LICENSE.txt, resources/openapi-mt.json, resources/openapi.json
- `kamu repo list`: supports all types of output
- https://github.com/kamu-data/kamu-cli/pull/916
- Tests: `sqlx + nextest` combination has been stabilized 
- https://github.com/kamu-data/kamu-cli/pull/919
- `DatasetEntryIndexer`: guarantee startup after `OutboxExecutor` for a more predictable initialization 
- https://github.com/kamu-data/kamu-cli/pull/921
- Add `DatasetEntry`'is re-indexing migration
- `kamu push`: show correct error if server failed to store data 
- https://github.com/kamu-data/kamu-cli/pull/918
=> Release (patch): 0.206.1

CHANGELOG.md, Cargo.lock, Cargo.toml, LICENSE.txt, images/demo/user-home/01 - Kamu Basics (COVID-19 example)/init-chapter-2.sh, resources/openapi-mt.json, resources/openapi.json, src/infra/core/src/remote_alias_resolver_impl.rs
=> Fix panic with odf repo

src/e2e/app/cli/common/src/kamu_api_server_client_ext.rs, src/e2e/app/cli/inmem/tests/tests/commands/test_verify_command.rs, src/e2e/app/cli/inmem/tests/tests/test_flow.rs, src/e2e/app/cli/inmem/tests/tests/test_smart_transfer_protocol.rs, src/e2e/app/cli/mysql/tests/tests/test_flow.rs, src/e2e/app/cli/postgres/tests/tests/commands/test_init_command.rs, src/e2e/app/cli/postgres/tests/tests/commands/test_verify_command.rs, src/e2e/app/cli/postgres/tests/tests/test_flow.rs, src/e2e/app/cli/postgres/tests/tests/test_smart_transfer_protocol.rs, src/e2e/app/cli/repo-tests/src/commands/test_inspect_command.rs, src/e2e/app/cli/repo-tests/src/commands/test_log_command.rs, src/e2e/app/cli/repo-tests/src/commands/test_search_command.rs, src/e2e/app/cli/repo-tests/src/test_flow.rs, src/e2e/app/cli/repo-tests/src/test_smart_transfer_protocol.rs, src/e2e/app/cli/sqlite/tests/tests/commands/test_verify_command.rs, src/e2e/app/cli/sqlite/tests/tests/test_flow.rs, src/e2e/app/cli/sqlite/tests/tests/test_smart_transfer_protocol.rs
=> E2E: do not use Risingwave

src/app/cli/src/commands/add_command.rs, src/e2e/app/cli/common/src/kamu_api_server_client_ext.rs, src/e2e/app/cli/repo-tests/src/test_flow.rs, src/utils/kamu-cli-puppet/src/kamu_cli_puppet_ext.rs
=> E2E, test_trigger_flow_hard_compaction(): stabilize

resources/cli-reference.md, src/app/cli/src/cli.rs
Add missing short version back
=> Add missing short version of sql --command parameter

src/e2e/app/cli/inmem/tests/tests/commands/test_init_command.rs, src/e2e/app/cli/postgres/tests/tests/commands/test_pull_command.rs, src/e2e/app/cli/sqlite/tests/tests/commands/test_pull_command.rs
=> Correct test groups for `make test-fast`

CHANGELOG.md, Cargo.lock, Cargo.toml, LICENSE.txt, images/kamu-base-with-data-mt/extra/.kamuconfig, resources/openapi-mt.json, resources/openapi.json
Closes: #966
- `kamu-base-with-data-mt` image building
=> Release `0.208.1`

CHANGELOG.md, src/domain/flow-system/domain/src/repos/flow/flow_event_store.rs, src/domain/flow-system/services/src/flow/flow_scheduling_helper.rs, src/domain/flow-system/services/tests/tests/test_flow_executor_impl.rs, src/infra/flow-system/inmem/src/flow/inmem_flow_event_store.rs, src/infra/flow-system/postgres/src/postgres_flow_event_store.rs, src/infra/flow-system/repo-tests/src/test_flow_event_store.rs, src/infra/flow-system/sqlite/src/sqlite_flow_event_store.rs
Closes: https://github.com/kamu-data/kamu-cli/issues/967
=> Fix flow trigger after restart

CHANGELOG.md, deny.toml, src/app/cli/src/commands/login_command.rs, src/e2e/app/cli/repo-tests/src/commands/test_login_command.rs
Closes: https://github.com/kamu-data/kamu-cli/issues/970
=> Login command add url with odf schema

CHANGELOG.md, src/app/cli/src/explore/web_ui_server.rs
=> Typo corrected in feature flags

CHANGELOG.md, src/app/cli/src/cli_commands.rs, src/app/cli/src/commands/system_api_server_run_command.rs, src/app/cli/src/explore/api_server.rs, src/app/cli/src/explore/mod.rs, src/app/cli/src/explore/ui_configuration.rs, src/app/cli/src/explore/web_ui_server.rs
Closes: #868
Runtime configuration for UI is separated into two parts:
- actual runtime configuration (static content, determined by the deployment environment or `kamu ui`)
- dynamic UI configuration (defines function properties and feature flags determined by the server)
=> 868 api server provide feature flags for UI

resources/schema.gql, src/adapter/graphql/src/queries/flows/flow_event.rs, src/domain/flow-system/domain/src/aggregates/flow/flow.rs, src/domain/flow-system/domain/src/entities/flow/flow_event.rs, src/domain/flow-system/domain/src/entities/flow/flow_state.rs, src/domain/flow-system/services/src/flow/flow_scheduling_helper.rs, src/domain/flow-system/services/tests/tests/test_flow_executor_impl.rs, src/domain/flow-system/services/tests/tests/utils/manual_flow_trigger_driver.rs
Closes: https://github.com/kamu-data/kamu-cli/issues/938
=> Fix manuan trigger config merge

.github/workflows/build.yaml
This change fixes the CI agent pre-configuration for `Test / macOS /arm64`.
=> CI, build: use GITHUB_TOKEN for cargo-nextest installation

CHANGELOG.md, src/domain/flow-system/services/src/flow/flow_agent_impl.rs, src/domain/flow-system/services/tests/tests/test_flow_agent_impl.rs, src/domain/task-system/domain/src/entities/task_status.rs
Closes: https://github.com/kamu-data/kamu-cli/issues/1020
=> Update trigger status on flow fail

CHANGELOG.md, Cargo.lock, Cargo.toml, LICENSE.txt, resources/openapi-mt.json, resources/openapi.json
=> Patch release v0.217.3

CHANGELOG.md, Cargo.lock, Cargo.toml, LICENSE.txt, resources/openapi-mt.json, resources/openapi.json, src/adapter/auth-oso-rebac/src/oso_dataset_authorizer.rs, src/adapter/graphql/src/mutations/flows_mut/flows_mut_utils.rs, src/domain/core/src/use_cases/view_dataset_use_case.rs, src/infra/core/src/use_cases/commit_dataset_event_use_case_impl.rs, src/odf/metadata/src/dtos/dtos_extra.rs, src/odf/metadata/src/metadata/metadata_block_types.rs
- Private Datasets:
- Validation `SetTransform` event (input datasets): IDs are used for accessibility checks. 
Aliases are used only to generate an error message.
- `OsoDatasetAuthorizer`: readiness to handle duplicates when filtering
=> Private Datasets: process acceptance testing feedback: Vol. 1

CHANGELOG.md, src/adapter/graphql/tests/tests/test_auth.rs, src/app/cli/src/app.rs, src/domain/accounts/domain/src/messages/access_token_messages.rs, src/domain/accounts/domain/src/messages/account_messages.rs, src/domain/accounts/domain/src/messages/mod.rs, src/domain/accounts/services/Cargo.toml, src/domain/accounts/services/src/services/access_token_service_impl.rs, src/domain/accounts/services/tests/tests/mod.rs, src/domain/accounts/services/tests/tests/test_access_token_service_impl.rs
First part of implementing email for access token creation event
=> Add access token outbox message

Cargo.lock, src/adapter/flight-sql/Cargo.toml, src/adapter/graphql/Cargo.toml, src/adapter/http/Cargo.toml, src/adapter/http/tests/tests/test_data_query.rs, src/adapter/odata/Cargo.toml, src/app/cli/Cargo.toml, src/domain/core/Cargo.toml, src/domain/core/src/services/ingest/data_writer.rs, src/e2e/app/cli/repo-tests/Cargo.toml, src/e2e/app/cli/repo-tests/src/commands/test_log_command.rs, src/e2e/app/cli/repo-tests/src/commands/test_search_command.rs, src/infra/core/Cargo.toml, src/infra/core/src/services/ingest/fetch_service/evm.rs, src/infra/core/src/services/ingest/ingest_common.rs, src/infra/core/src/services/query_service_impl.rs, src/infra/ingest-datafusion/Cargo.toml, src/odf/data-utils/Cargo.toml, src/odf/data-utils/src/schema/convert.rs, src/odf/metadata/Cargo.toml, src/utils/datafusion-cli/Cargo.toml, src/utils/kamu-cli-puppet/Cargo.toml
Based on https://github.com/kamu-data/kamu-cli/pull/1062
Blocker:
- https://github.com/datafusion-contrib/datafusion-functions-json/pull/69
=> Upgrade datafusion 45

CHANGELOG.md, Cargo.lock, src/adapter/graphql/src/queries/datasets/dataset_metadata.rs, src/adapter/graphql/src/scalars/metadata.rs, src/adapter/graphql/tests/tests/test_gql_account_flow_triggers.rs, src/adapter/graphql/tests/tests/test_gql_metadata.rs
=> Fix dataset alias in metadata query

src/adapter/graphql/src/queries/datasets/dataset_metadata.rs, src/adapter/graphql/src/queries/datasets/metadata_chain.rs, src/adapter/graphql/src/scalars/metadata.rs, src/adapter/graphql/tests/tests/test_gql_metadata_chain.rs
=> Make metadata chain queries return correct aliases

CHANGELOG.md, src/adapter/auth-oso-rebac/src/oso_dataset_authorizer.rs, src/utils/repo-tools/src/release.rs
=> Private Datasets: post-deploy minor fixes

CHANGELOG.md, Cargo.lock, Cargo.toml, LICENSE.txt, images/kamu-base-with-data-mt/Makefile, images/kamu-base-with-data/Makefile, images/kamu-base-with-env-var-storage/Makefile, resources/openapi-mt.json, resources/openapi.json, src/adapter/auth-oso-rebac/tests/tests/test_oso_dataset_authorizer.rs, src/adapter/graphql/tests/tests/test_gql_datasets.rs, src/app/cli/src/app.rs, src/app/cli/src/database.rs, src/app/cli/src/services/workspace/workspace_layout.rs, src/app/cli/src/services/workspace/workspace_service.rs, src/app/cli/tests/tests/test_di_graph.rs, src/app/cli/tests/tests/test_system_info_command.rs, src/domain/auth-rebac/services/src/lib.rs, src/domain/auth-rebac/services/src/rebac_dataset_lifecycle_message_consumer.rs, src/domain/auth-rebac/services/tests/tests/mod.rs, src/domain/auth-rebac/services/tests/tests/test_rebac_dataset_lifecycle_message_consumer.rs, src/e2e/app/cli/inmem/tests/tests/commands/test_init_command.rs, src/e2e/app/cli/postgres/tests/tests/commands/test_init_command.rs, src/e2e/app/cli/repo-tests/src/commands/test_add_command.rs, src/e2e/app/cli/repo-tests/src/commands/test_init_command.rs, src/e2e/app/cli/repo-tests/src/commands/test_pull_command.rs, src/e2e/app/cli/sqlite/tests/tests/commands/test_init_command.rs, src/utils/kamu-cli-puppet/src/kamu_cli_puppet_ext.rs, src/utils/repo-tools/Cargo.toml, src/utils/repo-tools/src/release.rs
---
Closes: #981 
- The usage of local database (SQLite) is activated by default for all single tenant workspaces
- Improved error message for SQL parsing method for queries which includes invalid or reserved keywords
=> `[Deployment Instructions]` Release (minor): `0.224.0` + Use SQLite database in single-tenant Kamu-CLI case too

CHANGELOG.md, src/infra/ingest-datafusion/src/writer.rs
=> Treat view types equivalent to regular in schema compatibility check

CHANGELOG.md, src/app/cli/src/app.rs, src/app/cli/src/services/config/models.rs, src/domain/task-system/domain/src/services/task_agent.rs, src/domain/task-system/services/src/task_agent_impl.rs, src/domain/task-system/services/tests/tests/test_task_agent_impl.rs
Closes: https://github.com/kamu-data/kamu-cli/issues/1005
=> Add external flow system configuration

CHANGELOG.md, Cargo.lock, Cargo.toml, LICENSE.txt, images/kamu-base-with-data/.gitignore, images/kamu-base-with-data/README.md, images/kamu-base-with-data/init-workspace-minio.sh, images/kamu-base-with-data/init-workspace.sh, resources/cli-reference.md, resources/openapi-mt.json, resources/openapi.json, src/app/cli/src/cli.rs, src/app/cli/src/cli_commands.rs, src/app/cli/src/commands/add_command.rs, src/app/cli/src/commands/pull_command.rs, src/app/cli/src/commands/push_command.rs, src/domain/core/src/utils/tenancy_config.rs, src/domain/datasets/services/Cargo.toml, src/infra/core/Cargo.toml, src/infra/core/src/services/sync/sync_service_impl.rs, src/infra/core/src/utils/simple_transfer_protocol.rs, src/infra/core/tests/tests/test_pull_request_planner_impl.rs
- TBA
- TBA
- TBA
---
- Single-tenant mode:
- `kamu add`: public default visibility, unless otherwise specified
- `kamu pull`: public new default visibility, unless otherwise specified
- Simple Transfer Protocol:
- Respect the visibility option
- Updating the dependency graph during block processing
=> `[Deployment Instructions]` Release (patch): 0.225.3

CHANGELOG.md, Cargo.lock, Cargo.toml, DEVELOPER.md, LICENSE.txt, images/demo/.gitignore, images/demo/Dockerfile.debug.jupyter, images/demo/Makefile, images/demo/README.md, images/demo/docker-compose.yml, images/demo/jupyter/kamu-start-hook.sh, resources/cli-reference.md, resources/openapi-mt.json, resources/openapi.json, src/app/cli/src/cli.rs, src/app/cli/src/cli_commands.rs, src/app/cli/src/services/odf_server/access_token_registry_service.rs
- TBA
- TBA
- TBA
---
- `kamu login`: only one argument `--user` (root) is left, other arguments (from subcommands) are removed
- Demo Jupyter start-up failure
=> `[Deployment Instructions]` Release (patch): 0.226.3

.github/pull_request_template.md, CHANGELOG.md, Cargo.lock, images/kamu-base-with-data/init-workspace-minio.sh, src/adapter/http/src/smart_protocol/axum_server_push_protocol.rs, src/adapter/http/src/smart_protocol/ws_tungstenite_client.rs, src/app/cli/src/commands/log_command.rs, src/domain/core/src/services/sync_service.rs, src/domain/datasets/domain/src/use_cases/append_dataset_metadata_batch_use_case.rs, src/domain/datasets/services/Cargo.toml, src/domain/datasets/services/src/use_cases/append_dataset_metadata_batch_use_case_impl.rs, src/domain/datasets/services/tests/tests/use_cases/test_append_dataset_metadata_batch_use_case.rs, src/e2e/app/cli/repo-tests/src/commands/test_delete_command.rs, src/e2e/app/cli/repo-tests/src/test_private_datasets.rs, src/infra/core/Cargo.toml, src/infra/core/src/utils/simple_transfer_protocol.rs, src/infra/core/tests/tests/test_pull_request_planner_impl.rs, src/infra/core/tests/tests/test_remote_status_service.rs, src/infra/core/tests/tests/test_search_service_impl.rs, src/infra/core/tests/tests/test_sync_service_impl.rs, src/infra/core/tests/tests/use_cases/test_push_dataset_use_case.rs, src/odf/dataset-impl/src/services/dataset_factory_impl.rs
Closes: #1112
- Simple Transfer Protocol & Smart Transfer Protocol use `AppendDatasetMetadataBatchUseCase`
=> Simple Transfer Protocol: `AppendDatasetMetadataBatchUseCase` integration

CHANGELOG.md, src/adapter/http/src/lib.rs, src/adapter/http/src/unknown_handler.rs, src/adapter/http/tests/harness/test_api_server.rs, src/adapter/http/tests/tests/mod.rs, src/adapter/http/tests/tests/test_unknown_handler.rs, src/app/cli/src/explore/api_server.rs, src/app/cli/src/explore/web_ui_server.rs
Closes: https://github.com/kamu-data/kamu-cli/issues/1092
=> Add unknown routes fallback handler

images/kamu-base-git/Dockerfile
=> `kamu-base-git`: explicit toolchain

CHANGELOG.md, src/odf/data-utils/src/data/format/json.rs, src/odf/data-utils/src/data/format/text.rs
=> Fix BinaryView and Utf8View json encoding

.github/workflows/release.yaml, CHANGELOG.md, Cargo.lock, Cargo.toml, LICENSE.txt, resources/openapi-mt.json, resources/openapi.json
- Simple Transfer Protocol & Smart Transfer Protocol use `AppendDatasetMetadataBatchUseCase`
- SQLite: protection against database locking, in case of parallel execution of `kamu` commands.
- Based on `journal_mode=WAL`
- GQL: speeding up work by reducing allocations
- API server correctly logs unknown routes
- GQL: `Search::query()`: fix regression resulting in unstable ordering of search results
- Fix JSON encoding of `BinaryView` and `Utf8View` data (#1127)
=> Release (patch): 0.226.4

Cargo.lock
Based on https://github.com/briansmith/ring/issues/2461#issuecomment-2705634778
=> Hotfix: CI release build

.github/workflows/release.yaml, CHANGELOG.md, Cargo.lock, Cargo.toml, LICENSE.txt, deny.toml, resources/openapi-mt.json, resources/openapi.json, src/adapter/graphql/src/queries/search.rs, src/utils/s3-utils/src/s3_context.rs, src/utils/s3-utils/src/s3_metrics.rs
Closes: #855
- Prometheus metrics, S3: fixed `storage_url` label values
=> Release (patch): `0.226.5`

CHANGELOG.md, images/demo/Dockerfile.jupyter, images/demo/Makefile, images/demo/docker-compose.yml, images/demo/jupyter/.kamuconfig, images/demo/podman/containers.conf, src/app/cli/src/explore/sql_shell_impl.rs
Closes: https://github.com/kamu-data/kamu-cli/issues/1098
=> Fix spark container spawn inside jupyter

CHANGELOG.md, resources/schema.gql, src/adapter/graphql/src/queries/accounts/account.rs, src/adapter/graphql/src/queries/accounts/account_flow_runs.rs, src/adapter/graphql/src/queries/datasets/dataset.rs, src/adapter/graphql/src/scalars/flow_configuration.rs, src/adapter/graphql/src/utils.rs, src/domain/flow-system/domain/src/services/flow/flow_query_service.rs, src/domain/flow-system/services/src/flow/flow_query_service_impl.rs, src/odf/dataset/src/services/dataset_handle_resolver.rs
Closes: #1150
- Private Datasets:
- GQL: Correct processing of access permissions when viewing flows of another account
=> GQL: `Account::flows()`: proper access check

CHANGELOG.md, src/adapter/graphql/src/scalars/flow_trigger.rs, src/adapter/graphql/tests/tests/test_gql_dataset_flow_triggers.rs, src/domain/flow-system/domain/src/entities/shared/batching_rule.rs, src/domain/flow-system/services/src/flow/flow_scheduling_helper.rs, src/domain/flow-system/services/tests/tests/test_flow_agent_impl.rs
Closes: https://github.com/kamu-data/kamu-cli/issues/1132
=> Add executing transform flow without root data changes 

CHANGELOG.md, resources/schema.gql, src/adapter/graphql/src/queries/flows/flow_description.rs, src/domain/core/src/services/dataset_changes_service.rs, src/infra/core/src/services/dataset_changes_service_impl.rs
Closes: https://github.com/kamu-data/kamu-cli/issues/1152
=> Return unknown respose for broken dataset flows

CHANGELOG.md, src/adapter/graphql/src/queries/flows/flow_description.rs, src/adapter/graphql/src/scalars/flow_trigger.rs
=> Followup minor changes

CHANGELOG.md, src/app/cli/src/app.rs, src/app/cli/src/cli.rs
Closes: #1102
- `kamu init`: in case of using `--pull-images` argument, fixed unclear error with not found file.
=> `kamu init`: in case of using `--pull-images` argument, fixed unclear error with not found file

CHANGELOG.md, src/app/cli/src/app.rs, src/app/cli/src/cli_commands.rs
Closes: https://github.com/kamu-data/kamu-cli/issues/1202
=> Trigger outbox_agent_ methods only for command that require it

.github/workflows/release.yaml, CHANGELOG.md, Cargo.lock, Cargo.toml, LICENSE.txt, resources/openapi-mt.json, resources/openapi.json
- GQL: Added new scalars: `Email`, AccountPassword`.
- GQL: Added `AccountMut::delete()`.
- GQL: Collection API: Add `ExtraData` scalar to validate incoming data.
- DB: Removed FK for `did_secret_keys.creator_id` 
- DB: Added missing triggers for deleting account rows (`ON DELETE CASCADE`) 
for related tables (`accounts_passwords`, `access_tokens`, `dataset_entries`).
- GQL: `AccountMut::modifyPassword()`: no longer accepts the `accountName` argument.
- GQL: `AccountMuts::createAccount()`: method moved from `AccountMut`.
- Refactor:
- Remove password logic from `AccountService` level.
=> Release (minor): 0.238.0

src/app/cli/src/app.rs, src/domain/accounts/services/src/services/login_password_auth_provider.rs, src/utils/init-on-startup/Cargo.toml, src/utils/init-on-startup/src/init_on_startup.rs, src/utils/init-on-startup/tests/test_init_on_startup.rs
Follow-up for https://github.com/kamu-data/kamu-cli/pull/1277
=> `init-on-startup`: `add JobSelector`

src/domain/accounts/domain/Cargo.toml, src/domain/accounts/domain/src/messages/account_lifecycle_message.rs, src/domain/accounts/services/src/services/did_secret_service.rs, src/domain/accounts/services/src/use_cases/modify_account_password_use_case_impl.rs, src/domain/accounts/services/tests/tests/use_cases/test_modify_password_use_case_impl.rs, src/domain/datasets/services/src/services/dataset_account_lifecycle_handler.rs, src/domain/datasets/services/src/services/dataset_alias_update_handler.rs
Follow-up for https://github.com/kamu-data/kamu-cli/pull/1277
=> AccountLifecycleMessage::PasswordChanged: introduce

CHANGELOG.md, src/adapter/graphql/src/queries/search.rs, src/adapter/graphql/tests/tests/test_gql_search.rs
Closes: https://github.com/kamu-data/kamu-cli/issues/1296
=> GQL Search also filters by id

resources/schema.gql, src/adapter/graphql/src/mutations/molecule_mut.rs, src/adapter/graphql/src/queries/molecule.rs, src/adapter/graphql/src/scalars/mod.rs, src/adapter/graphql/src/scalars/u256.rs, src/adapter/graphql/tests/tests/test_scalars.rs
=> `MoleculeMut::create_project()`: use `U256` type for `ipnft_token_id`

CHANGELOG.md, resources/schema.gql, src/adapter/graphql/src/mutations/dataset_mut/adapters_mut/collection_mut.rs, src/adapter/graphql/src/queries/datasets/dataset.rs, src/adapter/graphql/tests/tests/test_gql_dataset_adapter_collection.rs, src/domain/core/src/entities/writer_metadata_state.rs, src/domain/core/src/services/ingest/push_ingest_planner.rs, src/infra/core/src/services/ingest/push_ingest_planner_impl.rs
Closes: https://github.com/kamu-data/kamu-cli/issues/1299
=> Handle collection not found expected head err

CHANGELOG.md, src/adapter/graphql/src/queries/datasets/dataset.rs, src/e2e/app/cli/mysql/tests/tests/test_smart_transfer_protocol.rs, src/e2e/app/cli/postgres/tests/tests/test_smart_transfer_protocol.rs, src/e2e/app/cli/repo-tests/src/test_smart_transfer_protocol.rs, src/e2e/app/cli/sqlite/tests/tests/test_smart_transfer_protocol.rs
Closes: https://github.com/kamu-data/kamu-cli/issues/1336
=> Derived dataset resolved correctly with unaccessible inputs

CHANGELOG.md, Cargo.lock, src/infra/core/Cargo.toml, src/infra/core/src/services/ingest/prep_service.rs, src/odf/dataset/src/services/metadata_chain_visitor.rs
=> ringbuf: 0.4

CHANGELOG.md, src/adapter/flow-dataset/src/flow_controllers/flow_controller_ingest.rs, src/adapter/flow-dataset/src/flow_controllers/flow_controller_transform.rs, src/adapter/flow-dataset/src/flow_sensors/derived_dataset_flow_sensor.rs, src/adapter/flow-dataset/src/services/flow_datasets_event_bridge.rs, src/adapter/flow-dataset/tests/tests/flow_controllers/test_flow_controller_ingest.rs, src/adapter/flow-dataset/tests/tests/flow_controllers/test_flow_controller_transform.rs, src/adapter/flow-dataset/tests/tests/flow_sensors/test_derived_dataset_flow_sensor.rs, src/adapter/flow-dataset/tests/tests/services/test_flow_datasets_event_bridge.rs, src/adapter/flow-webhook/tests/tests/test_dataset_updated_webhook_sensor.rs, src/adapter/flow-webhook/tests/tests/test_flow_controller_webhook_deliver.rs, src/adapter/graphql/src/queries/flows/flow.rs, src/adapter/graphql/src/queries/flows/flow_event.rs, src/adapter/graphql/src/queries/flows/flow_start_condition.rs, src/adapter/graphql/tests/tests/test_gql_dataset_flow_runs.rs, src/domain/flow-system/domain/src/entities/flow/flow_activation_cause.rs, src/domain/flow-system/domain/src/entities/flow/flow_start_condition.rs, src/domain/flow-system/domain/src/entities/flow/flow_state.rs, src/domain/flow-system/services/src/flow/flow_scheduling_helper.rs, src/domain/flow-system/services/tests/tests/test_flow_agent_impl.rs, src/domain/flow-system/services/tests/tests/utils/flow_system_test_listener.rs
Contributes to [kamu-web-ui#735](https://github.com/kamu-data/kamu-web-ui/issues/735), flow history does not demonstrate the latest batching condition statistics, except for the 1st time.
=> Flows: each input contribution to batching rule is reflected as an update of start condition

CHANGELOG.md, Cargo.lock, migrations/postgres/20250903145548_dataset-entries_owner-name_lowercase.sql, migrations/sqlite/20250903145548_dataset-entries_owner-name_lowercase.sql, src/adapter/graphql/src/mutations/molecule_mut.rs, src/adapter/graphql/src/queries/search.rs, src/adapter/graphql/tests/tests/test_gql_custom_molecule.rs, src/adapter/graphql/tests/tests/test_gql_search.rs, src/utils/multiformats/Cargo.toml, src/utils/multiformats/src/stack_string.rs, src/utils/multiformats/tests/tests/mod.rs, src/utils/multiformats/tests/tests/test_stack_string.rs
:warning: Post-actions:
---
Related: #1285
=> `GQL: Search::query()`: case insensitive search

CHANGELOG.md, Cargo.lock, src/app/cli/src/services/config/models.rs, src/infra/core/Cargo.toml, src/infra/core/src/services/ingest/fetch_service/configs.rs, src/infra/core/src/services/ingest/fetch_service/evm.rs
Upgrades to latest `datafusion-ethers` and propagates new config parameters.
=> EVM source improvements

src/adapter/graphql/src/mutations/molecule_mut.rs, src/adapter/graphql/src/queries/molecule.rs
Continues work from:
- https://github.com/kamu-data/kamu-cli/pull/1313
=> Unify root span prefixes: Molecule part
